### ISSUE TITLE
Inventory Count Problem

### ISSUE THREAD

**Issue by antoinegali** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1004]
While you are completing an inventory count, if you input the quantity then scan the item SKU, it adds it to the list with "1" as quantity, not considering whatever number you put first. 
You then have to manually update the number of items

**Comment by MuhammadAdnan32** [comment]
Hi @antoinegali , 
Sure thing! Let me take a look to see if I'm getting the same issue as you and I'll circle back to you.
Thanks,
Regards,
M Adnan

**Comment by MuhammadAdnan32** [comment]
Hi @antoinegali ,
I hope you are doing well. I have checked your concern in case of scan we allow only one item to count because we can scan a single item at a time and quantity directly added to cart as you have seen. So we will not allow multiple items to count in case of the scan. If you want to count multiples items you can use bulk count option.
If you have any questions or if there is anything else with which I may assist, please do not hesitate to reach out.
Thanks,
Regards,
M Adnan

**Comment by antoinegali** [comment]
Hello,

Thanks for the reply. It seems like I didn't use the feature correctly. I think the actual way to do it is very convenient.

Thanks,
Antoine
