### ISSUE TITLE
Invoice email issue 

### ISSUE THREAD

**Issue by Omar1892** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1008]
![Screen Shot 2020-01-21 at 5 30 34 PM](https://user-images.githubusercontent.com/47898011/72858058-67965600-3c74-11ea-8944-e18d3f4a8637.png)
When ever I we try to send a receipt email or an invoice by email the costumer never gets it. I've tried to send it to my personal email as well and it doesn't arrive. I have reported this issue on my old account but you guys told me that it was working on your side, and since it was working with you guys, you guys didn't never fixed the issue on my side. Can you please check and see if I have everything enabled I have check the setting my self and it seems fine.

**Comment by MuhammadAdnan32** [comment]
Hi @Omar1892 , 
Adnan here 👋 Sure thing! Let me take a look to see if I'm getting the same issue as you and I'll circle back to you.
Thanks,

**Comment by MuhammadAdnan32** [comment]
Hi @Omar1892 ,
Thank you for bringing this to our attention! It looks like an account-specific issue.
I'm gonna reach out to our Engineers to get this taken care of, I'll get back to you as soon as I have more information! 
Thanks,
Regards,
M Adnan

**Comment by MuhammadAdnan32** [comment]
For internal use:
https://repairdesk.atlassian.net/browse/RB-814

**Comment by MuhammadAdnan32** [comment]
Hi @Omar1892 ,
I hope you are doing well. Kindly check the developer comment bellow.
We have checked our system is working fine. Emails are sending. but our SMTP blocking this email request because the sender email is from yahoo.com. It's highly recommended to not use any yahoo.com email for a store as the SMTP server considers it as a fake email request. please ask the customer  to change the store email to any other account (non-yahoo.) issue will be solved.
If you have any questions or if there is anything else with which I may assist, please do not hesitate to reach out.
Thanks,
Regards,
M Adnan

**Comment by Omar1892** [comment]
Ok, thank you for quickly getting back to me. Will this issue with the (yahoo) be fixed?

**Comment by MuhammadAdnan32** [comment]
Hi @Omar1892 ,
I hope you are doing well. We will not fix this issue because our SMTP blocking this email request and the SMTP server considers it as a fake email request.  It's highly recommended to not use any yahoo.com email for a store. Kindly change the store email to any other account (non-yahoo.).
If you have any questions or if there is anything else with which I may assist, please do not hesitate to reach out.
Thanks,
Regards,
M Adnan
