### ISSUE TITLE
Customer Estimates issue

### ISSUE THREAD

**Issue by tinkertechguy** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1061]
When creating customer estimates, it does not show up in their profile

**Comment by MuhammadAdnan32** [comment]
Hey @tinkertechguy ,
I hope you are doing well. Currently we don't have such functionality in our system. When you will convert estimate into ticket or invoice then  it will display on customer profile otherwise not.Only tickets and invoices are display on customer profile.
If you have any questions or if there is anything else with which I may assist, please do not hesitate to reach out.
Thanks,
Regards,
M Adnan
