### ISSUE TITLE
Creat ticket automatically when edit ticket

### ISSUE THREAD

**Issue by hitman1986** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1064]
When edit on ticket and save it When I choose not to create an invoice, I find that he created an invoice automatically even though I did not ask him to do so.
Even although not get to employee to creat ticket

**Comment by MuhammadAdnan32** [comment]
Hey @hitman1986 , 
Adnan here 👋 Sure thing! Let me take a look to see if I'm getting the same issue as you and I'll circle back to you.
Thanks,
Regards,
M Adnan

**Comment by MuhammadAdnan32** [comment]
Hi @hitman1986 ,
I hope you doing well.I have checked your concern at my end and its working fine for me.Can you please share a video?
Thanks,
Regards,
M Adnan

**Comment by hitman1986** [comment]
Im sended video to mr danish

**Comment by MuhammadAdnan32** [comment]
Hy @hitman,
Thanks for sharing the video with us.I will check and update you soon.
Thanks & Regards,
M Adnan

**Comment by MuhammadAdnan32** [comment]
Hy @hitman1986 ,
I hope you are doing well.I have checked on your account , system is creating the invoice on edit even if you cancelled it. The reason is that your trigger of "Don't auto create invoice on create create ticket" is disabled, that's why the system is creating the invoice.Kindly enable the trigger then it will be working for you.
Steps:
Go to Store setting
-Click on Module configuration
-Click on Tickets
-And enable the trigger of "Don't auto create invoice on Create Ticket.
-Save and verify at your end.
kindly see the attached image.
![Screenshot_9](https://user-images.githubusercontent.com/50608942/76389578-596bd880-638d-11ea-8ea3-692101e56cb1.png)
If you have any questions or if there is anything else with which I may assist, please do not hesitate to reach out.
Thanks,
Regards,
M Adnan

**Comment by hitman1986** [comment]
Thanks you👍
