### ISSUE TITLE
ticket counter display

### ISSUE THREAD

**Issue by gsmgps-star** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1075]
hi.
you are close this ticket..but issue is the same...text is not translated...
see picture: https://i.imgur.com/6qHsZd8.jpg

regards

_Originally posted by @gsmgps-star in https://github.com/Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS/issues/1006#issuecomment-601615625_

**Comment by MuhammadAdnan32** [comment]
Hey @gsmgps-star , 
Adnan here 👋 Sure thing! Let me take a look to see if I'm getting the same issue as you and I'll circle back to you.
Thanks,
Regards,
M Adnan

**Comment by gsmgps-star** [comment]
ok tnx

**Comment by MuhammadAdnan32** [comment]
Hey! @gsmgps-star ,
Thank you for bringing this to our attention! It looks like there's a bug that just popped up . 
I'm gonna reach out to our Engineers to get this taken care of, I'll get back to you as soon as I have more information! 
Thanks,
Regards,
M Adnan

**Comment by MuhammadAdnan32** [comment]
For internal use:
https://repairdesk.atlassian.net/browse/RB-1020

**Comment by MuhammadAdnan32** [comment]
Hi @gsmgps-star ,
I hope you are doing well. ​I have viewed and discussed your issue with the development team and developer comment is: All iframe’s created in system, no one is translated because iframe’s are  session less and language translator are work with store session. So Currently this is not possible.
If you have any questions or if there is anything else with which I may assist, please do not hesitate to reach out.
Thanks,
Regards
M Adnan
