### ISSUE TITLE
Improvements in Inventory Count | Joel Zeitman | iPhone Repair VB Birdneck

### ISSUE THREAD

**Issue by fahadimran303** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1114]
**Hi Sir,**

**Business Name | Store Name:**
Joel Zeitman | iPhone Repair VB Birdneck

**Customer Stature:**
2 Store Location with Annual Plan.
High Presence on Social Media.
Can help us a lot in other verticals as well.

**Module:**
Inventory Count

**Improvement:**
Customer has come up with a request that once we go to Inventory Count, he would like to:

1) Update Cost Price while updating the Inventory
2) Option to add New Item in Inventory in Inventory Count

**IMP:** They will not use the software untill we can go Live with this improvement. Might cancel as well

**Video:**
https://drive.google.com/file/d/1R8r9SM1eq1lNSxVa3lYBHio298QsU-Ty/view

**Source:**
https://app.intercom.com/a/apps/mq09yl4f/inbox/inbox/all/conversations/26795146819

**Thanks and Regards,**
Fahad Imran

**Comment by fahadimran303** [comment]
Internal Jira Link:
https://repairdesk.atlassian.net/browse/REP-2547

**Comment by fahadimran303** [comment]
Customer will not use the software untill we are going to go live with the improvement.

I will appreciate if you can share an update on when exactly this can be done so we can update customer accordingly. We can offer him free months in order to retain however we need to know when it will be Live.

**Comment by Uzair-RepairDesk** [comment]
@fahadimran303 
Hope you are doing well,  it is to inform you that we have made this (Update Cost Price while updating the Inventory)improvement live,  Based on the trigger in the setting part user can now update the cost price for those items which have increase in stock.
![FIXAPHONE_RepairDesk_InventoryCount_Config](https://user-images.githubusercontent.com/22955861/87665454-64da7080-c780-11ea-8af0-ecd0f39c4a34.png)
if the trigger is enabled then the user can update the cost price otherwise it will work as its working currently.
