### ISSUE TITLE
Changing Product Category need reminder/match WooCommerce Category.

### ISSUE THREAD

**Issue by BharatPRC** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1186]
There is a very easy option in the Inventory Management to change the product's category.
![2020-06-22_2040](https://user-images.githubusercontent.com/34261339/85278859-df3d0b00-b4c8-11ea-9678-18a82b35500a.png)

But when we change the category from here, it doesn't change or even asks if the category needs to be changed for WooCommerce store for this particular product.

However, there should be a popup / or trigger in the setting to remind user that the product is still synced in woo commerce in a different category.

**Comment by Uzair-RepairDesk** [comment]
Hey @BharatPRC 
I believe when you change the category of an item, it updates automatically on woocommerce when it syncs the data.
Did you try it at your end?

**Comment by BharatPRC** [comment]
It doesn't change.

I changed categories of lots of produvts, then later on I check in woocommwece but still products we're in the old categories.
First I was thinking that changes made on products are not syncing with woo. 
But later on I figure if, category is only changing in RD, I had to manually change each category manually. 

I still believe you didn't understand what I am trying to say exactly. 

If there is any confusion I can explain on Teamviewer etc.

**Comment by geelongmicrosoldering** [comment]
By default, the product is updated based on the SKU. Unless you specify otherwise in WooCommerce integration settings, nothing will be changed beyond the price and quantity. For example, the photo is uploaded once, and assumed to be there from then on.

This behaviour is usually best, because uploading a bunch of images you already have is a waste of resources (both on your server, and RD's).

I actually have products in multiple categories on WC end, so RepairDesk overwriting the placement of those products would be a problem. Updating based on SKU is what we want for our application.

That said, if you look in the integration settings, there is an option to sync categories first. I've never used it, but by understanding is that it forces the creation or modification of categories, prior to the sync of products.

Im not sure if it will help you at all, but its worth investigating exactly what that does. It could be what you are after

**Comment by Uzair-RepairDesk** [comment]
Thanks for the details @BharatPRC 
However is it possible to record the video for this case so I can share it with my engineering team so they can look into it in detail? Thanks

**Comment by BharatPRC** [comment]
http://sc.com.ly/show/RVymbhBSZjMlw2LaOGF1YpcNi0X34PC6

**Comment by BharatPRC** [comment]
have you checked the video ?
