### ISSUE TITLE
Woocommerce is syncing same image over and over

### ISSUE THREAD

**Issue by BharatPRC** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1220]
Woocommerce is syncing same image over and over and filling up the media files on website.
On any product update and information edit, same image got synced to woocommerce.

can we stop this if possible ?

Please have a look at the video.

http://sc.com.ly/show/RDqQEJ9Wt0g1i6dMvlPfxn3KsFYcrV5o

**Comment by usmanalikhan93** [comment]
Hi @BharatPRC 

I hope you are doing well. I have noted down your concern. I will discuss this with developer on Monday and update you on this,

**Comment by usmanalikhan93** [comment]
Hi @BharatPRC 

I hope you are doing well. I have discussed this with developer and he said due to this issue we have added this trigger "Sync product image on your online store when a product is updated on RepairDesk", So you need to disable this trigger and upload image manually on WooCommerce. For now this is only the solution we have.

**Comment by BharatPRC** [comment]
ok. thank you
