### ISSUE TITLE
System Splitten Transactions At Check Out 

### ISSUE THREAD

**Issue by Omar1892** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1223]
The video was sent to adnan@repairdesk.co

**Comment by MuhammadAdnan32** [comment]
Hi @Omar1892 ,
Received and thank you for sharing. 
Adnan here 👋 Sure thing! Let me take a look to see and I'll circle back to you.
Thanks & Regards,
M Adnan

**Comment by MuhammadAdnan32** [comment]
Hi @Omar1892,
I hope you doing well. I have checked your mentioned issues in the video.
1-In case if we add more payment the system is showing change due which we have to give back to the customer. That's why system is showing like this, if you will add 1$ and invoice amount is 0.50$ then the system will show you 0.50 in change due.
2-For second case it's working fine. I have doubled checked If we add payment using Offline credit card it's working fine. Kindly check at your end do let us know if you face the same problem again.
If you have any questions or if there is anything else with which I may assist, please do not hesitate to reach out.
Thanks & Regards,
M Adnan

**Comment by Omar1892** [comment]
@MuhammadAdnan32 Ok, thank you. Ill keep on checking the system. and if it happens again i will mention it on here. Please don't close this issue.

**Comment by Repairdesk-QA** [comment]
Hello @Omar1892,
Hope you are doing well.

Since I haven't heard back from you, I’m assuming you're all set for now, but you can always give me a shout here if anything else comes up!
Waiting for your response.

**_Regards,_**
Quratul Ain

**Comment by Repairdesk-QA** [comment]
Hello @Omar1892,
Hope you are doing well.

Since I haven't heard back from you, I’m assuming you're all set for now, but you can always give me a shout here if anything else comes up!
Closing this issue for now, but you can always open this whenever you want to.

**_Regards,_**
Quratul Ain
