### ISSUE TITLE
Prices don't change after being updated 

### ISSUE THREAD

**Issue by Omar1892** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1293]
Hello, 

I've sent a video regarding this issue to fahadimran85@gmail.com

**Comment by MuhammadAdnan32** [comment]
Hey @Omar1892 , 
Adnan here Sure thing! Let me take a look to see if I'm getting the same issue as you and I'll circle back to you.
Thanks & Regards,

**Comment by MuhammadAdnan32** [comment]
Hey @Omar1892 ,
I hope you doing well. I have checked your concern on your account and seen that you have set sale price with the device issue and we have a high priority of sale price instead of the retail price. So, if you have set a sale price of a repair problem then it will not change with retail on POS when you set it. If you want to change prices on the runtime of the repair problem on POS then you have to clear the sale price from the repair problem.
If you have any questions or if there is anything else with which I may assist, please do not hesitate to reach out.
Thanks & Regards,
M Adnan

**Comment by Omar1892** [comment]
@MuhammadAdnan32 Hello, I really understand your feedback. Usually we would be able to change the price from the button it self and the price would update automatically. In this case, we can update the price but once the price is saved with in the button it will not updated. It will remain at the same old price.

**Comment by MuhammadAdnan32** [comment]
Hey @Omar1892 ,
I hope you are doing well. If you have set a sale price of a repair problem then it will be updated only from  Inventory=>Manage services=>Repairs=>update the repair problem=>Update sale price then it will be updated on POS as well. And If you want to change prices on the runtime of the repair problem on POS then you have to clear the sale price from the repair problem as we have a high priority of sale price instead of the retail price.d
If you have any questions or if there is anything else with which I may assist, please do not hesitate to reach out.
Thanks & Regards,
M Adnan
