### ISSUE TITLE
Repair buttons 

### ISSUE THREAD

**Issue by Omar1892** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1300]
Hello, 

The I was going through Repair Buttons under manage repair and services and I notice that when I looked up certain models such as the iPhone 8 a lot of the service were missing from their. But when I would go to the POS system under problems all the buttons that are missing from the back end are showing in the POS system under problems. Can you please look in to this. 
![Screen Shot 2020-09-10 at 10 26 46 AM](https://user-images.githubusercontent.com/47898011/92772585-b2bebf80-f350-11ea-8c1b-2f74c7cefdea.png)
![Screen Shot 2020-09-10 at 10 26 36 AM](https://user-images.githubusercontent.com/47898011/92772702-cbc77080-f350-11ea-880e-918345b2e247.png)
![Screen Shot 2020-09-10 at 10 26 14 AM](https://user-images.githubusercontent.com/47898011/92772705-cc600700-f350-11ea-99f4-c4b018a514d9.png)

**Comment by MuhammadAdnan32** [comment]
Hey @Omar1892 ,
I hope you are doing well. I have looked into your concern, In current functionality, problems are mapped with devices and not mapped with the repair category. That's why the system is showing more repair problems on POS because these are mapped with the Devices. If you want to match the result then kindly apply the device filter on the manage repair services page and then look into POS it will show the same results. 
If you have any questions or if there is anything else with which I may assist, please do not hesitate to reach out.
Thanks & Regards,
M Adnan

**Comment by Omar1892** [comment]
Hello,

I've I looked in to it before bring this issue up, but the buttons are not appearing in the category they are supposed to be in. And they don't appear in any other category as well. This happen after my system cracked and you guys had to restore my account 4 days back.
