### ISSUE TITLE
SMS Problem with accent

### ISSUE THREAD

**Issue by JessicaSOS** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1312]
Hello,
We have sentence templates already made for texting. However, when the customer receives the message, full punctuation marks are displayed instead of the normal text accents.
See example text:

Bonjour Maxime Perron, 
votre appareil a été réparé et est maintenant prêt à être récupéré. 
SOS Phone Limoilou

We've had issues like this in the past and it had been fixed, but it's now back.
![texto bizarre](https://user-images.githubusercontent.com/40500094/93646478-4b4de300-f9d4-11ea-9e31-64fd0563480d.jpg)

--
french: Bonjour,
Nous avons des modèles de phrases déjà faite pour les textos. Cependant, lorsque le client recoit le message, plein de signe de ponctuation s'affiche au lieu des accents normaux du texte.
Voir exemple du texte: 

Bonjour Jessica Fugère, 
votre appareil a été réparé et est maintenant prêt à être récupéré. 
SOS Phone Limoilou

Nous avons déjà eu des problèmes de ce genre dans le passé et sa l'avait été corrigé, mais c'est maintenant revenue.

**Comment by usmanalikhan93** [comment]
Hi @JessicaSOS 

I hope you are doing well. I just to ask from you that can I made a test on your account ? And do let me know any template in which you were facing issue. 

Regards,
Usman Ali

**Comment by JessicaSOS** [comment]
Of course you can! This is the SMS related to the completed repair. See red box. There is also the same problem with all SMS including among others the one framed in blue also.
<img width="944" alt="notiff" src="https://user-images.githubusercontent.com/40500094/94066788-f555b280-fdba-11ea-8597-1c2476224014.png">

**Comment by JessicaSOS** [comment]
We still have this problem, is someone working on it?

**Comment by Repairdesk-QA** [comment]
Hey @JessicaSOS,
I hope you are doing well. Sorry for the inconvenience, we will look into it again and revert back to you early next week. I will reach out to you if I need more information. Thanks!

**Comment by Repairdesk-QA** [comment]
Hello @JessicaSOS,
Hope you are doing well.

We sincerely apologize for the inconvenience and we have released a fix for this issue. Can you please confirm if you are still getting the same issue?
Kindly let us know about your feedback.

**_Regards,_**
Quratul Ain

**Comment by Repairdesk-QA** [comment]
Hello @JessicaSOS,
Hope you are doing well.

Since I haven't heard back from you, I’m assuming you're all set for now, but you can always give me a shout here if anything else comes up!
Closing this issue for now, but you can always open this whenever you want to.

**_Regards,_**
Quratul Ain

**Comment by Repairdesk-QA** [comment]
Hey @JessicaSOS,
I hope you are doing well. 
Sorry for the continued inconvenience. Sure thing! Let me take a look to see if I'm getting the same issue as you and I'll circle back to you.
Regards, 
Ayesha Aamir

**Comment by Repairdesk-QA** [comment]
Hey @JessicaSOS,
I hope you are doing well. 

I have checked the reported issue in detail and tested it along with one of our senior developer. We have checked from the backend and tested with the same SMS body as you mentioned above but everything seems to work fine on our end as you can see in the screenshots attached below. Quite possible this issue is from **Clickatell SMS Integration end and it can be region specific**.
But for now, what I am doing is creating a task for our Engineering team so that they can further investigate the reported issue in detail and I'll get back to you as soon as I have more information! 

![Clickatell](https://user-images.githubusercontent.com/39614480/145961703-be033c32-40c7-4654-b5a8-d82333f379bf.png)
![Repair Shop RepairDesk - Update EmailContent](https://user-images.githubusercontent.com/39614480/145961711-5839bab3-ee1f-450e-a61f-51a456fdf531.png)

@JessicaSOS I want to ask you that can I make a test SMS entry on your account?
Your patience would be highly appreciated.
Thanks,
Ayesha Aamir

**Comment by Repairdesk-QA** [comment]
**For internal use only:**
https://repairdesk.atlassian.net/browse/RB-4280

**Comment by JessicaSOS** [comment]
ok, i'm waiting for your return

**Comment by Repairdesk-QA** [comment]
**Hey @JessicaSOS,**
**I hope you are doing well.**

I have tested the reported issue in detail along with one of our senior developer and found that everything is working fine on our end, and there is something not right on **Clickatell Integration end** i.e. I have tested with the same Ticket SMS body as that available in your RepairDesk account but the issue is not reproduced on test account but reproduced on your account. 

The thing is if the issue was from our end then by putting the same SMS body (copied from your account) issue should reproduce on our end as well but it didn't. So the only possibility is that this issue is from the Clickatell SMS Integration end and it can be region-specific. 

Kindly discuss this issue with **Clickatell Integration support team** and share the attached screenshots that I'm attaching for your reference with them so that they can get this problem fixed for you. 

**Your account test screenshots:**
<img width="960" alt="SOS Phone LimoilouRepairDesk - Customerdetail Customer" src="https://user-images.githubusercontent.com/39614480/146754308-397a72b9-05b2-4e5d-81c8-e21b559cc463.png">


<img width="960" alt="clickatell Jessica account" src="https://user-images.githubusercontent.com/39614480/146754324-507e901c-0d01-40ff-88be-a92490d7b6cd.PNG">


**My account test screenshot:**
<img width="960" alt="clickatell my account" src="https://user-images.githubusercontent.com/39614480/146754392-d819fc6d-873c-49bc-8360-bf774b2e16dc.PNG">


And I hope that if there’s anything else I can do for you, you won’t hesitate to let me know.
**_Thanks,_**
**_Ayesha Aamir_**

**Comment by JessicaSOS** [comment]
Thank you for checking out. For your information, the problem is not the currency, I tried to change it and the problem is still present. I will contact Clickatell for the rest of this problem.

Have a good day
