### ISSUE TITLE
Manufacturers can't be deleted.

### ISSUE THREAD

**Issue by adigsm07** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1318]
Hi! This days I delted some old devices and I want to delete some Manufactureres but I can't. The problem is very old, have 6 months and it's still here.  Can you make something with this error/bug ?

Screenshot with error --> https://ibb.co/S02qVLv

**Comment by usmanalikhan93** [comment]
Hello @adigsm07 

I hope you are doing well. I have checked your concern and found that there is a repair in your account which has this Manufacturer. So if you want to delete this manufacturer, you have to delete this repair first then delete this device and then you can delete manufacturer because they are interlinked with each other. Hope this help. 
![image](https://user-images.githubusercontent.com/39614480/94104221-f7b61c00-fe4f-11ea-87ed-6a28ad5a94c5.png)

Regards, 
Usman Ali

**Comment by usmanalikhan93** [comment]
Hi again @adigsm07 - since I haven't heard back from you, I’m assuming you're all set for now, but you can always give me a shout here if anything else comes up!
