### ISSUE TITLE
FreePBX  View ticket button

### ISSUE THREAD

**Issue by Shane-RepairDesk** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1332]
![Capture](https://user-images.githubusercontent.com/60683772/94759398-c9639f80-036d-11eb-9bd2-3286e272f138.PNG)
![Capture2](https://user-images.githubusercontent.com/60683772/94759404-cbc5f980-036d-11eb-9e8b-5c16e142793f.PNG)

The View ticket button is forwarding to a login screen, It was opening the actual ticket.

**Comment by MuhammadAdnan32** [comment]
Hey @Shane-RepairDesk , 
Adnan here Sure thing! Let me take a look to see if I'm getting the same issue as you and I'll circle back to you.
Thanks & Regards,

**Comment by MuhammadAdnan32** [comment]
Hey @Shane-RepairDesk ,
I hope you are doing well. I have checked your concern but unfortunately, I am unable to reproduce your issue.
Would be great if you can check it again at your end and if the issue is still there please do let us know. It may be an account-specific issue or browser cache or session expire issue.
If you have any questions or if there is anything else with which I may assist, please do not hesitate to reach out.

**Comment by Shane-RepairDesk** [comment]
Cleared cache etc.,   Does on all machines and employee's homes.

**Comment by Uzair-RepairDesk** [comment]
@Shane-RepairDesk 
Is it possible to test it from your account? You can provide relevant credentials of your account and PBX at adnan@repairdesk.co and uzair@repairdesk.co
Looking forward to hearing from you.

**Comment by Shane-RepairDesk** [comment]
@Uzair-RepairDesk Will DM credentials on Monday out of town.

**Comment by Uzair-RepairDesk** [comment]
ok @Shane-RepairDesk
