### ISSUE TITLE
Unable to process payments when tickets are imported from another branch if they have the same ticket ID

### ISSUE THREAD

**Issue by iCellsouthcity** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#134]
![new](https://cloud.githubusercontent.com/assets/23712887/20740719/54a68d9e-b72a-11e6-8a2c-4cb9c66de5ed.jpg)

![image](https://cloud.githubusercontent.com/assets/23712887/20740690/06bb0fb0-b72a-11e6-923d-5143e332f0a9.png)

When we import a repair ticket from another branch and if we have the same job number for another job that was booked under our branch we can not process the payment for the job that we imported from the other branch.

**Comment by HafizAnas** [comment]
Hi @iCellsouthcity, 
Sorry for Inconvenience. Let me check at our end and revert back to you soon.

**Comment by Repair-Desk** [comment]
@iCellsouthcity 

We are sorry about processing payment issue. 

You might be facing this issue because **Ticket ID** needs to be unique among all stores. To avoid this issue I would recommend you to update ticket number initial i.e. C-101 or I-101 for all locations. 

**Here is a guide on how you can update ticket ID:** **https://repairdesk.uservoice.com/knowledgebase/articles/922107-how-do-i-change-ticket-numbers**

Can you try updating ticket ID initial for all stores and let me know if it works again after that?
