### ISSUE TITLE
Ticket Assigned Staff Bugged

### ISSUE THREAD

**Issue by TechTraders** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1350]
The assigned to drop down for tickets are bugged. 

in the general queue it shows who is assigned to it but when you open the ticket every ticket is listed as unassigned

see photos below.

![Capture](https://user-images.githubusercontent.com/68912093/96054195-77ba2980-0ec4-11eb-9789-6a471726a339.PNG)
![Captur3e](https://user-images.githubusercontent.com/68912093/96054202-7a1c8380-0ec4-11eb-9e6f-7ceeaa449f3b.PNG)

**Comment by Repairdesk-QA** [comment]
Hey, 
Afnan here 👋 Sure thing! 
Let me take a look to see if I'm getting the same issue as you and I'll circle back to you.

**Comment by Repairdesk-QA** [comment]
Hello @TechTraders 

Hope you are doing well and staying safe.

I have just checked your issue and found out that your employee named "johnathan honhke" is no more on your employee list. If you delete an employee then on the ticket listing page it still shows the assignee name. If you open the same ticket in edit mode ticket will be unassigned because the employee has been deleted.

To sort out this out you need to assign this ticket to another employee. Hope it helps.

If there is anything else we can do for you please let us know.

Regards,
RepairDesk Team

**Comment by TechTraders** [comment]
Right i Understand. thanks for clarifing
