### ISSUE TITLE
Part Price issues 

### ISSUE THREAD

**Issue by Omar1892** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1364]
If you look at picture one the price for a product says that its $14.01 and when that same item is looked up on the inventory on hand and price the price for the same item is at $0.38 

![Screen Shot 2020-10-21 at 3 53 16 PM](https://user-images.githubusercontent.com/47898011/96798568-0394ef80-13b6-11eb-858f-69d472a18484.png)

![Screen Shot 2020-10-21 at 3 50 30 PM](https://user-images.githubusercontent.com/47898011/96798525-ec560200-13b5-11eb-8571-34e44134002b.png)

**Comment by Repairdesk-QA** [comment]
Hey @Omar1892 ,

Hope you are doing well and staying safe.

I have checked this on different tickets and found out that it showing the exact price on every ticket. Please have a look at the attached image.
![omer](https://user-images.githubusercontent.com/39614480/96843725-8001ef80-1403-11eb-8993-d0cbe59478f1.PNG)
Can you please specify the ticket number?

Regards,
Afnan Mahmood

**Comment by Omar1892** [comment]
Hello, I had to fix the prices manually. You have to add a second repair to a ticket that has being created for the issue to replicate.

**Comment by Repairdesk-QA** [comment]
Hey @Omar1892,

Thanks for the confirmation about the case. I have tested this and found the reason. Tow parts are bundled with a repair problem
(A)Mobile > (A) Apple parts > iPhone 8 > (A) Screen white code 25 > here you can find two parts bundled one with cost $0.38 and the other is with cost $14.04. Due to this, it's showing $14.04 cost as well. You need to un-bundle the second part from pos. 
Item Id: 340 is with cost $14.04 and Item ID: 413 with cost $0.38
Please un-bundle these items to sort this out. If you want me to un-bundle these items then please mention.

Hope it helps.

Regards,
Afnan Mahmood
