### ISSUE TITLE
Improvement in Inventory Bundles Module | Rogastan Ellis | Fiks-IT Shop 85711

### ISSUE THREAD

**Issue by fahadimran303** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1391]
**Hi Sir**,

**Business Name**:
Fiks-IT Shop

**Customer Stature**:
1 Store on Enterprise Package with Annual Plan.
High Presence on Social Media.
Can help us a lot in other verticals as well.

**Module**:
Inventory Bundles

**Improvement**:

The customer logged 2 improvement request, which are as followed:

- He should be able to search/scan a service bundle using its SKU just like we can search/scan the SKU of a product bundle.
- The Product Bundle tab on the POS screen should be named as Bundles and all the bundles should be categorized under this tab respectively.

Kindly find the attached video for more details on the customer's request.

**Video**:
https://drive.google.com/file/d/18ydUS0c-W1csqTEaJWeaA_QoJ60U7EFq/view

**Source**:
Intercom

_Thanks and Regards_,

**Faisal Ali**

**Comment by fahadimran303** [comment]
Jira link:
https://repairdesk.atlassian.net/browse/REP-3006

**Comment by Uzair-RepairDesk** [comment]
Hey, @fahadimran303  hope you are doing well,  service bundle is associated with the tickets so we can not give the option to simply search them by SKU, if the user wants to use the service bundle he can only use them while creating a ticket,  so that is not possible. The same reason is that we can not show all the bundles separately in a  tab. Hope this helps 

Regards,
Humza Mehmood
