### ISSUE TITLE
Estimate not letting us to change date

### ISSUE THREAD

**Issue by BharatPRC** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1409]
if i want to edit date on esitmate it goes to year 1970.
and another bad thing is : when we update, 
it ONLY giving two option, Send for approval and Approve quote.
what if , after updating thickt we want to reveiew it ?
like in my scenario, it sent couple of emails to customer with wrong date.
have a look at the video 

http://sc.com.ly/show/iuzkmpAyVfR325X1YD7PIdg4NbUJsnFl

**Comment by BharatPRC** [comment]
other annoying things is , whatever we do with ticket, it is just sending emial to customer automatialy, 
and there is no trigger to stop it.
what is this guys ?

**Comment by Uzair-RepairDesk** [comment]
Hey, @BharatPRC  Hope you are doing well.
sure thing I will check the date issue at my end and circle back to you.
2nd thing, we are already adding the option to just save an estimate upon update so that you can review them. will keep you posted once it's done.
3rd we have functionality that every time an estimate is created email is sent to the customer for approval, but if you want to stop sending automatic email for approval then you need to turn it off from email notification settings.
![image](https://user-images.githubusercontent.com/22955861/99929303-88d14280-2d6e-11eb-901a-d7e7a1149ec4.png)

Hope this helps.

Regards,

**Comment by Repairdesk-QA** [comment]
For internal use:
https://repairdesk.atlassian.net/browse/RB-2101

**Comment by Repairdesk-QA** [comment]
Hey @BharatPRC ,
I hope you are doing well. Your reported issue related to "Estimate not letting us change date" has been fixed. Please verify at your end and do let us know if you have questions.

Thanks! & Regards,
M Adnan
