### ISSUE TITLE
Error with Canned Responses for SMS

### ISSUE THREAD

**Issue by iTechConnectionsWC** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1456]
![RD_Issue](https://user-images.githubusercontent.com/77811200/105419056-1b298180-5c0c-11eb-8a24-bb36e2ce3938.png)
There are duplicates of different canned responses and there is no option to edit or delete them. I would also like to have the ability to edit these canned responses like we can for the automatic text messages. I would like to have the option to remove the name of repairs from the SMS and just have the name of the device by either editing the macros used for templates or by just editing the canned responses.

**Comment by Repairdesk-QA** [comment]
Hey @iTechConnectionsWC, 
Adnan here Sure thing! Let me take a look to see if I'm getting the same issue as you and I'll circle back to you.
Thanks & Regards,

**Comment by Repairdesk-QA** [comment]
Hey @iTechConnectionsWC,

You can edit the canned responses from web app Emails & Notifications settings by simply clicking on the Action button and then hit the Update button present against every canned response as marked in the screenshot attached below. Currently, the user cannot delete any canned response from the web app but if you want to remove duplicate canned responses then kindly highlight them so that I can request our development team to remove them from the backend for you. 

![Canned responses settings](https://user-images.githubusercontent.com/39614480/105804582-fa717b00-5fc1-11eb-828f-346183f4a04d.png)

Further, I have checked your second concern which is related to Device macro as currently, it is part of the functionality that whenever Device macro is used in any canned response it displays the problem name along with it. I will discuss your concern with our business analysis team and will update you accordingly. 

I hope that if there’s anything else I can do for you, you won’t hesitate to let me know.

Thanks & Regards,
Ayesha Aamer

**Comment by Repairdesk-QA** [comment]
Hi again @iTechConnectionsWC  - since I haven't heard back from you, I’m assuming you're all set for now, but you can always give me a shout here if anything else comes up!
