### ISSUE TITLE
Primary unticked when editing ticket under "Manage Tickets"

### ISSUE THREAD

**Issue by jphansendk** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1460]
We suddenly have to tick "Primary" under phone number when we edit a ticket. For some reason it's unticed when we access "edit ticket"? How can we fix this? All the tickets with this "bug" is added via the API? Was not a problem until mid last week?

**Comment by Repairdesk-QA** [comment]
Hey @jphansendk,
I hope you are doing well. We sincerely apologize for the inconvenience, this issue is already in our notice and we are working on it. Hopefully, the fix will be available with our next release which is planned for next week. We really appreciate your patience.
Thanks & Regards,
Ayesha Aamer

**Comment by Repairdesk-QA** [comment]
For internal use:
https://repairdesk.atlassian.net/browse/RB-2488

**Comment by Repairdesk-QA** [comment]
Hey @jphansendk,
I hope you are doing well. I believe this issue has been fixed in the recent update. Can you give it another try?
Thanks,
Ayesha Aamir

**Comment by Repairdesk-QA** [comment]
Hello @jphansendk,
Hope you are doing well.

Since I haven't heard back from you, I’m assuming you're all set for now, but you can always give me a shout here if anything else comes up.
Closing this issue for now, but you can always open this whenever you want to.

**_Regards,_**
Quratul Ain
