### ISSUE TITLE
Module - Check status verification on our website 

### ISSUE THREAD

**Issue by adigsm07** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1470]
Hello. On our website, we have integrated a module for checking the status of repairs from RepairDesk. The problem of this module is with translated sentences/ words.  Is translated in Romanian language but not correct. How to edit these words? 

Link from our website: https://www.gsmzone.ro/verificare-status-reparatie/
![RF](https://user-images.githubusercontent.com/65545272/106723908-46e73700-6610-11eb-838a-e516a0581b36.png)

**Comment by Repairdesk-QA** [comment]
Hey @adigsm07,
Ayesha here. I hope you are doing well. You can edit the words in the repair tracker widget by just simply following these steps i.e. Open Integration settings > select "Language Editor" > click on the "Edit" button present against the default "English" Language > select "Order LookUp Widget" option > edit the template as per your requirements > once done with editing kindly refresh your site page in order to reflect the changes. The reference screenshot is attached below. 
Hope it helps. Please let me know if I am able to answer your question. Thanks.
 
![Language Editor](https://user-images.githubusercontent.com/39614480/106746589-90517980-6644-11eb-899b-443ab06890e1.png)

**Comment by Repairdesk-QA** [comment]
Hi again @adigsm07 - since I haven't heard back from you, I’m assuming you're all set for now, but you can always give me a shout here if anything else comes up!
