### ISSUE TITLE
Goods Note Received cannot be deleted

### ISSUE THREAD

**Issue by technofuse** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1496]
I can't delete or undo a Goods Note received if I make a mistake. Just using the inventory adjustment feature isn't the correct way to adjust the inventory.

**Comment by Uzair-RepairDesk** [comment]
Hi, @technofuse  Hope you are doing well. By default, there is no option to Deleted GRN, because once GRN is created against a specific purchase order stock is updated and on-hand quantity is increased.
But if you want a specific GRN to be deleted then you can contact over support representative and he can do that needful. 

Hope it helps
