### ISSUE TITLE
Allow modification of retail price of special order part.

### ISSUE THREAD

**Issue by screenfixing** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1541]
We had an instance where the special order part was put in and a GRN and PO were created. We needed to update/add the retail cost of the part back in to the special order part but we were unable to modify the retail price. 

We can I guess modify the unit cost, but that does not impact tax. This impacts the final reporting for sales tax and other things as far as profitability. Retail cost should be required on inventory and special order parts (unless you only charge unit cost).

**Comment by Uzair-RepairDesk** [comment]
Hi, @screenfixing  Hope you are doing well, while creating a special order you can add the retail price as shown in the image attached below.
![image](https://user-images.githubusercontent.com/22955861/111946898-388ca600-8afe-11eb-80ba-ede03d58f2b1.png)
whereas the option to edit part retail price is not possible for now.
We have marked it under enhancements of the Special order module. We can certainly see how suggested improvements would be useful. We are short-staffed because of COVID 19. We have to pick new enhancements based on the value they’ll add to the most users possible. At the moment, we won’t be able to make this one however we can consider it in the future while updating the special order feature in RepairDesk 2.0.
I really appreciate that you took the time to share your idea. Thanks for helping us make this a platform you'll depend on.

Thanks,
