### ISSUE TITLE
Some invoices paid via stripe have unpaid status

### ISSUE THREAD

**Issue by creator72** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1564]
Some of my invoices in "invoices" list have the status "unpaid" but when you view the invoice its marked as "paid". no matter what I do, in the list view it remains status "unpaid".

**Comment by Repairdesk-QA** [comment]
Hey @creator72,
I hope you are doing well. I believe this issue has been fixed in the recent update. Can you give it another try? 
Plus the fix will only work on the newly created invoices, for the already created ones you just need to edit the invoice and hit the save button without changing anything & the system will automatically update the invoice status as paid on the Manage Invoice Listing page. And I hope that if there’s anything else I can do for you, you won’t hesitate to let me know.
Thanks,
Ayesha Aamer

**Comment by Repairdesk-QA** [comment]
Hye @creator72, 
Ayesha here. I hope you are doing well. Since I haven't heard back from you, I’m assuming you're all set for now, but you can always give me a shout here if anything else comes up. Thanks!

**Comment by creator72** [comment]
Hi, I'm still testing this to see if it still happens, It didn't happen with all my invoices just some. I have another more urgent problem, that Zettle will not login on the POS app for IOS, when trying to login it comes up with an error about a URI not allowed, I have chatted with he team about it but I need this working ASAP as it's a hassle using the zettle go app to take payment then recording it in repair desk. Its not professional when we're dealing with a customer at their address.

**Comment by Repairdesk-QA** [comment]
Hey @creator72 ,

Sorry for the inconvenience we are looking into this hopefully it will be fixed soon.

Please let me know if there anything else I can help you with.

Thanks, 
Zain
