### ISSUE TITLE
2 devices in 1 tickets. (Checkout just for 1 device)

### ISSUE THREAD

**Issue by adigsm07** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1583]
Hello, 
What's the procedure when a customer have 2 devices and we put in the same ticket and 1 device is done but 1 still remains for repair? How to make checkout for 1 device?

**Comment by Repairdesk-QA** [comment]
Hey @adigsm07,
Hope you are doing well. At the moment if a customer has 2 devices and we put in the same ticket and 1 device is done but 1 still remains for repair then you can take partial payment against that ticket during checkout & mark the Repaired & Collected status as No in the checkout pop-up so that the status of your respective ticket don't get change. Once the other problem is repaired you can checkout against the same ticket again & can pay the remaining amount. Hope it helps.
Thanks,
Ayesha Aamer

**Comment by Repairdesk-QA** [comment]
Hi again @adigsm07, since I haven't heard back from you, I’m assuming you're all set for now, but you can always give me a shout here if anything else comes up!
