### ISSUE TITLE
Bug: Can't enter SKU code longer than 7 characters in primary inventory screen, modern view.

### ISSUE THREAD

**Issue by onebitetechnology** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1599]
Can't enter SKU code longer than 7 characters in primary inventory screen, modern view.

**Comment by Repairdesk-QA** [comment]
Hey @onebitetechnology,

Working fine on our test account Can you please share a screenshot it will be helpful to us.

Please let me know if there anything else I can help you with.

Thanks,
Zain

**Comment by Repairdesk-QA** [comment]
Hi again @onebitetechnology,  since I haven't heard back from you, I’m assuming you're all set for now, but you can always give me a shout here if anything else comes up!

**Comment by onebitetechnology** [comment]
https://user-images.githubusercontent.com/80067352/121410882-45ac7a80-c920-11eb-92c3-0b473458d89b.mov

**Comment by Repairdesk-QA** [comment]
Hey @onebitetechnology,
I hope you are doing well. I believe this issue has been fixed in the recent update. Can you give it another try? If still, you face this issue try clearing your cache, cookies, logout, and log in to your account. 
If this doesn’t work or you have more questions, just let me know and I’ll be happy to help!
Thanks,
Ayesha

**Comment by onebitetechnology** [comment]
Solved: I had barcode set to EAN8, had to change to Code 128 :)
