### ISSUE TITLE
Warranty on receipt is different than actual

### ISSUE THREAD

**Issue by onebitetechnology** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1623]
My iPad/iPhone screen replacements have a lifetime warranty. 

The service has a lifetime warranty, the part has a lifetime warranty. 

On the receipt however, it is printing it as a "60 Day" warranty.

**Comment by Repairdesk-QA** [comment]
Hello @onebitetechnology,
I hope you are doing well! I have checked your concern but unfortunately, I am unable to reproduce your issue. Would be great if you can share a video of this issue or detailed steps so we can release a fix during our next release. You can put together a video using **Screencastify**. Or you can connect with one of our support agent on live chat so that he can look into the issue you are facing in detail. Thanks!

Regards,
Ayesha

**Comment by onebitetechnology** [comment]
https://youtu.be/mgaH-eRFu8I

**Comment by Uzair-RepairDesk** [comment]
@Repairdesk-QA 
Please check

**Comment by Repairdesk-QA** [comment]
Hi @onebitetechnology!
Definitely strange! I have investigated on my end and it seems to be working fine. But still, thanks for the steps to reproduce the video it helped a lot, and happy to know that it worked for you will discuss this further with our development team. 
If you have any questions or if there is anything else with which I may assist, please do not hesitate to reach out.
Thanks, 
Ayesha

**Comment by Repairdesk-QA** [comment]
For internal use:
https://repairdesk.atlassian.net/browse/RB-3344

**Comment by Repairdesk-QA** [comment]
Hey @onebitetechnology,
I hope you are doing well. We have scratched the system on your query and there's something definitely not working properly which is causing the issue, however, we are still trying to reproduce it at our end, hopefully, as soon your issue is reproduced it will be resolved!
If you have any questions or if there is anything else with which I may assist, please do not hesitate to reach out.
Thanks,
Ayesha
