### ISSUE TITLE
Price change on POS is buggy. Variable price like Square POS is needed

### ISSUE THREAD

**Issue by geekszoneva** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1644]
It would be very helpful if there is a variable price for products and services instead of all fixed prices. 

Also, there is a bug. When I try to change the price of the product or service on POS it changes the price and then when I add more products or services to the POS and click checkout it changes the price back to the old price. It is very annoying.

**Comment by Repairdesk-QA** [comment]
Hey @geekszoneva ,
Hope you are doing well.

I would like to inform you that it is not possible for us at this time to do **Variable Price Improvement** as we are short staff due to Covid. If you want to change your price, you can do it on the go while adding items to the cart.

AND 

For the **bug**, I have double-checked it at my end and unable to reproduce this issue. Can you please check it again at your end? If the issue still persists, please help us by **sharing a video** of this issue or detailed steps so we can release a fix during our next release. You can put together a video using **Screencastify**.

If you have any questions or if there is anything else with which I may assist, please do not hesitate to reach out.

Thanks & Regards,
Quratul Ain
