### ISSUE TITLE
Device/s chosen disappear on "add item" screen after clicking save

### ISSUE THREAD

**Issue by SpaceyPuppy** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1649]
Hey, I've noticed a quirk of the add item screen, when I go to save an item after filling out the details which includes choosing a device or devices it is used with, when I click the save button the "Select devices" box goes blank again. If I don't choose the device/s again after making any other modifications to the item settings it then clears the device choice and restores the value of N/A.

**Comment by Repairdesk-QA** [comment]
Hey @SpaceyPuppy 
Azka here.
Hope you are doing well.
Can you please elaborate on your concern and related video or screenshots? . Will be happy to help you once you share additional details.
Thanks & Regards.

**Comment by SpaceyPuppy** [comment]
Hi Aska. Please bear with me and I will do a video of the problem.

**Comment by SpaceyPuppy** [comment]
https://youtu.be/oPhVYyqX_7c

**Comment by Repairdesk-QA** [comment]
Hey @SpaceyPuppy 
Hope you are doing well.

I checked onto your concern and observed:
1) Item details are not mandatory fields to add an item. So there is a possibility that items are being 
added without details. because system cannot remove added information.

2) When you try to add device without manufacturer, it gets disappeared because devices belongs to manufacturer.
here correct flow is to add manufacturer first then add devices.

Hope it helps. Please let me know if I am able to answer your question. 
Thanks.
Azka
