### ISSUE TITLE
Critical Issue In Self Check-In for non mobile service businesses 

### ISSUE THREAD

**Issue by JNLogan** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1661]
Flagging something I have seen has been raised on the boards numerous times;

We have recently integrated Self Check-In Widget to our new site - the inability to hide the "Passcode" field as you can with the other fields makes the feature too confusing for non-mobile repair businesses to make use of the great feature. 

Would also be good to make address field mandatory.

Thanks

<img width="1356" alt="Screen Shot 2021-07-22 at 6 51 22 pm" src="https://user-images.githubusercontent.com/87804595/126613768-82ffd62d-8d1b-4a38-bee8-68ce95c83cda.png">

**Comment by Repairdesk-QA** [comment]
Hey @JNLogan 
Azka here.
I hope you are doing well. 
Thank you for sharing your need with us. I can certainly see how suggested improvements would be useful for our clients. Let me take a look to see how we can help you. I'll get back to you soon.
Thanks & Regards.

**Comment by Repairdesk-QA** [comment]
hey @
I hope you are doing well.
Thank you for reaching out to us and helping us make this a platform you'll depend on.
I believe this issue has been fixed in today's update. Can you setup self checkin again and give it another try?
If you have any questions or if there is anything else with which I may assist, please
do not hesitate to let me know.
Regards
Azka
