### ISSUE TITLE
Customer portal ticket grid ( listing ) view. Invoice column displays wrong info. 

### ISSUE THREAD

**Issue by alliedcomputers** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1669]
Steps
* Login to customer portal
* Click Tickets ( from menu)
* Check Ticket listing page "Invoice Id" column.
![Capture](https://user-images.githubusercontent.com/87709069/127645456-2dfcf538-26ab-4902-a75d-756102039c10.PNG)

Bug: "Invoice ID " column showing wrong info. The invoice number displays is not associated with that particular ticket. 
( image attached)

**Comment by Repairdesk-QA** [comment]
Hey @alliedcomputers 
Azka here.
I hope you are doing great.
Thank you for bringing this to our attention. It looks like there's a bug that just popped up. I'm gonna reach out to our Engineers to get this taken care of. I'll get back to you as soon as I have more information. 
Thanks

**Comment by Repairdesk-QA** [comment]
For internal use only:
https://repairdesk.atlassian.net/browse/RB-3585

**Comment by Repairdesk-QA** [comment]
Hey @alliedcomputers 
I hope you are doing well.
Thank you for reaching out to us and helping us make this a platform you'll depend on.
I believe this issue has been fixed in today's update. Can you give it another try?
If you have any questions or if there is anything else with which I may assist, please
do not hesitate to let me know.
Regards
Azka
