### ISSUE TITLE
Diagnose note & pre repair device condition not appearing on print preview ( ticket)

### ISSUE THREAD

**Issue by alliedcomputers** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1700]
Please check the video. 
Ticket copy print preview, doesnt show prerepair device condition and diagnose note. 

https://user-images.githubusercontent.com/87709069/133419893-db46c6fd-79f4-42ce-a4ad-cace40384b75.mp4

**Comment by Repairdesk-QA** [comment]
Hey @alliedcomputers, 
Hope you are doing well.

Sure thing! Let me take a look to see if I'm getting the same issue as you and I'll circle back to you.

Regards,
Quratul Ain

**Comment by Repairdesk-QA** [comment]
Hello @alliedcomputers,
Hope you are doing well.

I have checked your issue & able to find the reason.
One of our developers checked from Backend that the service(**backend id 4667**)  you are using in the mentioned ticket **RMA-171** has been deleted.
You can check your **services** from 
**Inventory -> Manage Services -> Repairs**
That's why it is not displaying Pre-repair device conditions and Diagnostic notes.
You can check your deleted inventory from **Employee Activity Report** and in Action, select Delete Inventory and Press Ctrl+F and type 4667.
For more clarification, here I am attaching picture of the test account with all filters.
![image](https://user-images.githubusercontent.com/39614480/133957399-2ca95e93-03e5-4fac-ab34-7167466636ae.png)

I hope this will solve your problem and If you still have any questions, please do not hesitate to reach us.

 Thanks & Regards,
 Quratul Ain

**Comment by Repairdesk-QA** [comment]
Hi again @alliedcomputers,
Hope you are doing well.

Since I haven't heard back from you, I’m assuming you're all set for now, but you can always give me a shout here if anything else comes up!
Please let me know if you have any questions.

**Regards,**
Quratul Ain
