### ISSUE TITLE
Estimates for product converting to tickets instead of invoices

### ISSUE THREAD

**Issue by AbbyCSC** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1737]
I create an estimate that is all products (no service) when I approve it is converting as ticket instead of invoice.  I have an estimate like this now that you can look at.

**Comment by Repairdesk-QA** [comment]
Hello @AbbyCSC,
Hope you are doing well.

Let me take a look to see if I'm getting the same issue as you and I'll circle back to you.
Your patience would be highly appreciated.

**_Regards,_**
Quratul Ain

**Comment by Repairdesk-QA** [comment]
Hi @AbbyCSC ,
Hope you are well!
Ayesha here. I have gone through the above mentioned issue and it seems that I will need more information regarding the issue.
I will request you to schedule a call with **Fahad Imran, Manager Customer Success and Support**. Kindly book a slot from the link in order to connect with him:
https://calendly.com/fahadimran
I am sure he will be able to assist with the above query and take relevant information so we can address your concerns timely.
Thank you!

**Comment by Repairdesk-QA** [comment]
Hi again @AbbyCSC, since I haven't heard back from you, I’m assuming you're all set for now, but you can always give me a shout here if anything else comes up!
Regards,
Ayesha Aamir

Closing this task for now.

**Comment by AbbyCSC** [comment]
While we were unable to figure out why inventory products were sometimes appearing as service on estimates, I now know how to fix when this happens so this can be closed.
Thank you

Abby Katz
Purchasing Manager
Computer SuperCenter of Greenwich
103 Mason St
Greenwich CT 06830
203-661-1700 option 2 Service
203-242-8654 direct line

**Comment by Repairdesk-QA** [comment]
Hey @AbbyCSC,
I hope you are doing well. Thanks for the update on this. And I hope that if there’s anything else I can do for you, you won’t hesitate to let me know.
Have a good day!
Regards,
Ayesha Aamir
