### ISSUE TITLE
Some Mobile Sentrix SKUs not showing up

### ISSUE THREAD

**Issue by MyPhoneRepair** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1743]
I just integrated MobileSentrix to R.D and got the main majority of inventory that they offer. 
However, there are some parts that don't show up in Repairdesk. I can scan the barcode on M.S and it shows up with the item, so I know they aren't out of stock on anything. I've gone through multiple times trying to add any more inventory on the integration page and I have 0 SKUs to download. Any help would be appreciated a lot!

**Comment by Repairdesk-QA** [comment]
Hey @MyPhoneRepair,
I hope you are doing well. Sorry for the continued inconvenience. There can be multiple reasons for not importing the complete Mobile Sentrix inventory to your RepairDesk account, so can you please connect with one of our support agent on live chat so that he can look into the issue you are facing in detail?
Thanks & Regards,
Ayesha Aamir

**Comment by Repairdesk-QA** [comment]
Hi again @MyPhoneRepair, since I haven't heard back from you, I’m assuming you're all set for now, but you can always give me a shout here if anything else comes up!
Regards,
Ayesha Aamir
