### ISSUE TITLE
recurring payment error

### ISSUE THREAD

**Issue by AMott-2020** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1795]
i am getting this error
![IMG_3835](https://user-images.githubusercontent.com/79152498/147775086-5a1cb590-43be-4771-8d9d-fe04f23ed3fe.jpg)
.

**Comment by Repairdesk-QA** [comment]
Hello @AMott-2020,
Hope you are doing well.

Sure thing! Let me take a look to see if I'm getting the same issue as you and I'll circle back to you.

**_Regards,_**
Quratul Ain

**Comment by Repairdesk-QA** [comment]
Hello @AMott-2020,

I would like to inform you that we will get this error when we have an Invalid Card Number.
Kindly review it again and let us know if you still have any issues.

**_Thanks & Regards,_**
Quratul Ain

**Comment by AMott-2020** [comment]
still having the issue.

**Comment by Repairdesk-QA** [comment]
Hello @AMott-2020,
Hope you are doing well.

Let me take a look to see if I'm getting the same issue as you and I'll circle back to you.

**_Thanks & Regards,_**
Quratul Ain

**Comment by Repairdesk-QA** [comment]
Hello @AMott-2020,
Hope you are doing well.

It seems to be an account-specific issue. One of our support ninjas will reach out to you to get more information.
OR
You can schedule a call with **_Fahad Imran, Manager Customer Success and Support._** Kindly book a slot from the link in order to connect with him:
https://calendly.com/fahadimran
I am sure he will be able to assist with the above query and take relevant information so we can address your concerns timely.

**_Thanks & Regards,_**
Quratul Ain

**Comment by Repairdesk-QA** [comment]
Hello @AMott-2020,
Hope you are doing well.

Kindly schedule a call with **_Fahad Imran, Manager Customer Success and Support_**. Kindly book a slot from the link in order to connect with him:
https://calendly.com/fahadimran
I am sure he will be able to assist with the above query and take relevant information so we can address your concerns timely.

**_Thanks & Regards,_**
Quratul Ain

**Comment by Repairdesk-QA** [comment]
Hello @AMott-2020,
Hope you are doing well.

Kindly share your Business Name associated with RepairDesk so it will be easy for us to contact you.
Waiting for your response.

**_Regards,_**
Quratul Ain

**Comment by Repairdesk-QA** [comment]
Hello @AMott-2020,
Hope you are doing well.

Since I haven't heard back from you, I’m assuming you're all set for now, but you can always give me a shout here if anything else comes up!
Closing this issue for now, but you can always open this whenever you want to.

**_Regards,_**
Quratul Ain
