### ISSUE TITLE
Scanning items with a "/" is changing the character to a "é"

### ISSUE THREAD

**Issue by techm89** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1807]
Let's say I have a barcode sku named: IPAD5/6. 

In the inventory module when I scan the barcode on the ticket of the product it pulls: IPAD5é6 instead of IPAD5/6. Seems like the system is switching / for an é automatically. It started doing this this week.

Can this be fixed? It's kind of annoying to have to replace the é with an /  manually each time we scan an accessory.

Thanks

**Comment by Repairdesk-QA** [comment]
Hello @techm89,
Sure thing! Let me take a look to see if I'm getting the same issue as you and I'll circle back to you.
Your patience would be highly appreciated.

**_Regards,_**
Quratul Ain

**Comment by Repairdesk-QA** [comment]
Hello **@techm89**,
Hope you are doing well !

I have checked your concern, it seems its an Account Specific Issue. Would be great if you can share a video of this issue or detailed steps. You can put together a video using Screencastify. If you have any questions or if there is anything else with which I may assist, please do not hesitate to reach out.

**Note: Kindly share your Business Name associated with Repairdesk Account**

**Regards,** 
Nida Khalid

**Comment by Repairdesk-QA** [comment]
Hello **@techm89,** 
Hope you are doing well !

Since I haven't heard back from you, I’m assuming you're all set for now, but you can always give me a shout here if anything else comes up! 
I have taken your **Business Name** from your other GIT issue. I have check your concern  with one of our senior Developers on your account associated with Repair Desk. . I'm unable to reproduced this issue even in your account. Would be great if you can share a video of this issue or detailed steps to reproduced. You can put together a video using Screencastify. 

Regards, 
Nida Khalid
