### ISSUE TITLE
Self Check-In Widget Phone without +1

### ISSUE THREAD

**Issue by mrfixdowntown** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1816]
Hello! I am using Self Check In Widget on iPad in my stores and customers creating self check in tickets there, unfortunately phone number automatically adding without +1 and after that repair desk don't recognize this number. Please, fix it.

**Comment by Repairdesk-QA** [comment]
Hey @mrfixdowntown, 
Ayesha here. Sure thing! Let me take a look to see if I'm getting the same issue as you and I'll circle back to you.

**Comment by Repairdesk-QA** [comment]
Hey @mrfixdowntown,
I hope you are doing well.

At present, we are not working on the new features/bug fixing on the Mobile App and iPad app for the next few months as one of the feedback we constantly receive is to simplify RepairDesk, make it more stable, and remove unnecessary options. With that in mind, we've decided to pause working on iPad & Mobile app and over the course of the next few months our entire team will be working on "RepairDesk 2.0"
It's going to be clean, fast, and reliable! I hope you'll like it!

**Workaround: For now you can add customers using Self Check-In with Customer Facing Display from the iPad app instead of adding customers from iPad POS else you can use the web app for the same purpose and the issue will be get fixed for you.** 

Hope it helps.

Thanks,
Ayesha Aamer
