### ISSUE TITLE
"Ready to Ship" status showing as a CLOSED ticket

### ISSUE THREAD

**Issue by roccor2gaming** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1820]
Good day. In Manage tickets, our tickets with the status "Ready to Ship" are showing up a CLOSED tickets. We would like these tickets to remain OPEN until the goods ship. Can you please assist?

Attached is an example for reference. Thank you,[
[Ready to Ship - closed ticket example.pdf](https://github.com/Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS/files/7989603/Ready.to.Ship.-.closed.ticket.example.pdf)

**Comment by Repairdesk-QA** [comment]
Hey @roccor2gaming,
I hope you are doing well. 

I have checked on your RepairDesk account from backend, and came to know that the custom status that you made i.e. **Ready to Ship** its Type = Closed that's why the tickets are Closed once this TICKET status is associated with them. If you want these tickets to stay **Open** after associating this status then kindly change **Ready to Ship** status Type = Open. 

**You can do this from Settings > Order Status > Ticket Status > Ready to Ship > Action > Edit > Type.**

Hope it helps and I hope that if there’s anything else I can do for you, you won’t hesitate to let me know.

Thanks, 
Ayesha Aamir
