### ISSUE TITLE
Estimates showing 0 value

### ISSUE THREAD

**Issue by AVECorp** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1828]
Hi Team,

When we create an estimate using a custom ticket status the estimate is showing as a $0 value, despite having a cost on the ticket.
If we try with one of the default system statuses then the estimate shows the correct amount.

**Comment by Repairdesk-QA** [comment]
Hello @AVECorp,
Hope you are doing well.

I have checked your issue and is working fine on our end.
**_Kindly look into the video attached:_**
https://watch.screencastify.com/v/zy6ijT48oDtxzDnRPS1z

Would be great if you share your business name with us so that we can check the settings you have made from the backend.
You can also provide us with a short video to elaborate on the steps that lead you to the issue.

Your patience and help mean a lot to RepairDesk.
Waiting for your kind response.

**_Thanks & Regards,_**
Quratul Ain

**Comment by Repairdesk-QA** [comment]
Hi again @AVECorp   - since I haven't heard back from you, I’m assuming you're all set for now, but you can always give me a shout here if anything else comes up!
