### ISSUE TITLE
[SHOPIFY] - [SYNC] - [Images / Description / Price Cost]

### ISSUE THREAD

**Issue by drphonemb** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1857]
Hi Guys. I got all products from Mobile Sentrix using Mobile Sentrix integration, then after i did Repair Desk vs Shopify, using data from Mobile Sentrix. I just realize the cost price and images doesn't sync with Shopify, that means i don't have cost price and images in my Shopify.

**Comment by Repairdesk-QA** [comment]
Hey **drphonemb**, Hope you are doing well !

Sure thing! Let me take a look to see if I'm getting the same issue as you and I'll circle back to you.

**_Regards,_** 
Nida Khalid

**Comment by Repairdesk-QA** [comment]
Hello **_drphonemb_**, Hope you are doing well !

Thank you for bringing this to our attention! It looks like there's a bug that just popped up. Will update you soon.

**_Regards_**,
Nida Khalid

**Comment by Repairdesk-QA** [comment]
**For Internal Use** 

**Jira Link:** https://repairdesk.atlassian.net/browse/RB-4970

**Comment by Repairdesk-QA** [comment]
Hello **_drphonemb_**, Hope you are doing well !

It is to inform you that your mentioned issue about image syncing to Shopify is fixed now, you may update the existing item or sync newly added Mobile Sentrix item in RepairDesk to Shopify.

Secondly the Cost Price issue is under Development Team, I'll get back to you as soon as I have more information about the fix! 

**_Regards,_**
Nida Khalid

**Comment by Repairdesk-QA** [comment]
**For Internal Use

Jira Link:** https://repairdesk.atlassian.net/browse/RB-5005

**Comment by Repairdesk-QA** [comment]
Hello **drphonemb**, Hope you are doing well !

Your reported issue has been fixed. Now when the Tigger **"Sync product cost price on your online store when a product is updated on RepairDesk"** is ON under Shopify Integration  , it will sync item's Cost Price with Shopify.

Also your concern related to image syncing was also fixed in our previous release. Please verify and do let us know.

And I hope that if there’s anything else I can do for you, you won’t hesitate to let me know.  

**_Regards,_**
Nida Khalid
