### ISSUE TITLE
Invoices / Estimates Not Allowing Products to be Backordered (RD1.0)

### ISSUE THREAD

**Issue by AVECorp** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1864]
Hi Team,

We have noticed the system does not show out of stock inventory products when creating an estimate or invoice.
Can this please be enabled so we are able to create backorders for parts we may not have on hand at the time of the estimate or enquiry.

Thank you

**Comment by Repairdesk-QA** [comment]
Hello @AVECorp,
Hope you are doing well.

I would like to add here that there are two triggers in 
Store Settings -> Module Configuration -> Point of Sale
If you enabled these triggers either for inventory or for parts, you would not be able to see Out of Stock items (neither on POS nor on estimates or invoices).
The triggers are highlighted in the picture,
![image](https://user-images.githubusercontent.com/39614480/170421950-944af633-c9a6-47e6-b13a-eaf7d4bbbfc1.png)

I believe you might have enabled one of these that's why your Out of Stock items are not visible.
If this is not the case, kindly share your business name and screenshot of the issue so we can check settings from the backend and will investigate in that way.

Waiting for your response.

**_Thanks & Regards,_**
Quratul Ain

**Comment by Repairdesk-QA** [comment]
Hi again @AVECorp   - since I haven't heard back from you, I’m assuming you're all set for now, but you can always give me a shout here if anything else comes up!
