### ISSUE TITLE
SUGGESTION Separate receipt and invoice channels

### ISSUE THREAD

**Issue by luisvae** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#229]
It would be great to have a separate channel for receipts and invoices. Some events are not worth of issuing an invoice, such as repairs to cost zero. 

It would be great that for every repair or sale a receipt was issue and creates the possibility of generating and invoice for the receipt or ticket.

**Comment by Repair-Desk** [comment]
@luisvae 

Thanks for your feedback. If you just want to create a receipt for a repair simply you **create ticket feature** on the point of sale because sometimes you can book in a water damage phone but its not repairable or you might create a warranty ticket with 0 value.

Incase you want to issue invoice simply hit checkout and it will create a ticket and invoice as well.

Hope it helps
