### ISSUE TITLE
Tax ID number

### ISSUE THREAD

**Issue by wirelessrepairzone** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#233]
I see someone also asked for the VAT number, here in the US we deal almost the same with a Tax ID number assigned to non-profits and government customers. We do the repairs for 4-5 school systems as well as a non-profit health care system. I have no way to configure the customer to default to no tax or record the tax ID number for the customer. This will be needed once the system is linked to quickbooks

**Comment by Uzair-RepairDesk** [comment]
Hi @wirelessrepairzone 
Hope you are doing great
I am glad to inform you that we have added the option to set a specific tax class against a customer and customer group so that you can mark the customer as tax exampt. While adding a new customer from manage customers section or from POS, tax class field can be selected and that will be applied when an invoice is created against that customer.

Let me know if you have any more concerns to share.

Thank you
