### ISSUE TITLE
Quickbooks integration broken

### ISSUE THREAD

**Issue by remarkasillem** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#273]
I have been using RD for several months - but the integration into QuickBooks only worked for the first 3 weeks.  Now trying to get it to manually transfer over the RD file has a broken integration, with no ability to check configuration as i get an error window.  

![image](https://user-images.githubusercontent.com/35260088/34719264-a7d8ca40-f581-11e7-8995-9554d987e2e0.png)

**Comment by Repair-Desk** [comment]
@remarkasillem We have recently released improvements in Quickbook integration. Are you still facing the same issue?

**Comment by remarkasillem** [comment]
I disconnected the integration when I wasn’t able to get any help on the issue..

With 1 month till end of financial year, I am happy to export CSV and import using a 3rd party app…

**Comment by Repair-Desk** [comment]
Thanks for the message, we'll get back to you as soon as
possible!

On May 29, 2018 at 5:38 PM Repair-DeskPOS/RepairDesk-Bugs
wrote:

I disconnected the integration when I wasn’t able to get any
help on the issue..

With 1 month till end of financial year, I am happy to export CSV
and import using a 3rd party app…

From: Repair-Desk

Sent: Tuesday, 29 May 2018 6:35 PM

To: Repair-DeskPOS/RepairDesk-Bugs

Cc: remarkasillem ; Mention

Subject: Re: [Repair-DeskPOS/RepairDesk-Bugs] Quickbooks
integration broken (#273)

@remarkasillem We have recently released improvements in
Quickbook integration. Are you still facing the same issue?

—

You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub, or mute the
thread.

--

You are receiving this because you were assigned.

Reply to this email directly or view it on GitHub:

https://github.com/Repair-DeskPOS/RepairDesk-Bugs/issues/273#issuecomment-392993374
( https://github.com/Repair-DeskPOS/RepairDesk-Bugs/issues/273#issuecomment-392993374 )

Powered by UserVoice. ( http://www.uservoice.com/powered-by?utm_campaign=poweredby&utm_medium=email&utm_source=ticket&uv_company=RepairDesk&uv_contact_url=repairdesk.uservoice.com&uv_experience=email )

**Comment by Uzair-RepairDesk** [comment]
QuickBooks integration is working fine since a while now. 
You can find more information on QuickBooks integration from the following link:-
https://repairdesk.uservoice.com/knowledgebase/articles/1200730-how-can-i-integrate-quickbooks-with-repairdesk
