### ISSUE TITLE
Printnode/Google Cloud Print - Rate Limiting results in lost print jobs

### ISSUE THREAD

**Issue by geelongmicrosoldering** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#319]
If any ip address tries to submit more than 10 jobs to printnode in any given second, printnode api returns a 429, and the job does not get printed. While it might seem like a rare occurrence, its not. It happens to RD users all the time, resulting in a success "your print job was sent" message for the RD user, but no document prints.

If you debug this, the job never even makes it to the printnode client server at all. I tested and confirmed this myself, using your own printnode child account credentials. 

I spoke to a developer from PrintNode, who told me that currently there was no way to increase the rate limit for a given ip or account, but we devised a way around it, which would be very simple to implement and is very easy to understand.

An example can be found here: https://pastebin.com/84N3zyXv

The idea is to keep the PHP executing with a while loop until the job is accepted, or 10 seconds has passed, whichever comes first. If the 10 second timeout is reached, an error is logged to your PHP error handler.

This way, the job is attempted to be sent a total of 100 times over a 10 second period. If for some reason printnode goes down, the PHP will still die after 10 seconds. If it goes down for a few seconds, or there are too many print jobs happening at once, they will pool in random order and eventually go through.

A few seconds delay for the print job coming out at POS, is way better than it never coming through at all.

You just need to adjust your printnode function to return the http response from PrintNode. Its really a 5 minute fix for a huge problem we should not be dealing with.

This issue also effects Google Cloud Print, although they have a rate limit of 20 requests/s

**Comment by Repair-Desk** [comment]
Sure thing! Let us take a look to see if we can optimize this and we will circle back to you.

**Comment by imiamran** [comment]
we have enabled trace log for printnode to see what's going on in background. it will help us to know if we are getting 429 code.

**Comment by Repair-Desk** [comment]
Thanks for the message, we'll get back to you as soon as
possible!

On May 30, 2018 at 9:36 PM Repair-DeskPOS/RepairDesk-Bugs
wrote:

we have enabled trace log for printnode to see what's going on
in background. it will help us to know if we are getting 429
code.

--

You are receiving this because you were assigned.

Reply to this email directly or view it on GitHub:

https://github.com/Repair-DeskPOS/RepairDesk-Bugs/issues/319#issuecomment-393399591
( https://github.com/Repair-DeskPOS/RepairDesk-Bugs/issues/319#issuecomment-393399591 )

Powered by UserVoice. ( http://www.uservoice.com/powered-by?utm_campaign=poweredby&utm_medium=email&utm_source=ticket&uv_company=RepairDesk&uv_contact_url=repairdesk.uservoice.com&uv_experience=email )

**Comment by geelongmicrosoldering** [comment]
The issue occurs for some users multiple times a day, so it shouldn't be long before you see it in the trace log.

I would advise you though, to look for anything other than 200, as opposed to specifically 429, which is how the PHP example is written (if httpcode != '200')
