### ISSUE TITLE
Store credit

### ISSUE THREAD

**Issue by kennexDEWA** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#338]
i could really use a store credit option that tracks credit for each customer.

Example, customer comes in for a repair, also wants to trade a phone in with us and use the trade in value for their repair.

Current work around is that i would purchase device for $X and use the "Cash" option to pay customer.

Then on their repair i would say ive taken $X in cash and charge them the difference.

Also if customer has store credit and they return to store, attempt to purchase services or product, an alert should pop up in POS module advising of available credit to use.

I belevie this could be a great asset to RD

**Comment by Uzair-RepairDesk** [comment]
Hi @kennexDEWA , @TechreviveAu 
Hope you are having a great time. 

I will gladly like to inform you that we have launched store credits module as an upgrade to our enterprise version. Now you can issue store credits, loyalty points and gift cards to your customers. 

Also you will be able to offer store credits instead of refunding an invoice to your customers and also purchase a trade in item by offering store credits. To learn more about our store credits module, please read the [Store Credits knowledgebase](https://help.repairdesk.co/knowledgebase/articles/1937059-how-to-use-store-credits-in-repairdesk) article. 

If you have any queries please don't hesitate to reach out to us. 

Thanks

**Comment by kennexDEWA** [comment]
Lol, way to late for my liking. I left your platform almost a year ago due to devs not fixing issues and simply adding more unstable features.

Remove me from your mailing list and cease all communication

**Comment by Uzair-RepairDesk** [comment]
Hey @kennexDEWA 

Thank you for your response. 
Our platform is quite stable now and we have introduced "Enterprise Version" with loyalty, gift card and store credits module that will help you to retain customers, increase efficiency and get more customers.

Want to know how RepairDesk has helped hundreds of repair stores in growing their businesses?
Read our customer [testimonials](http://www.capterra.com/p/146659/RepairDesk/#reviews) here and decide for yourself. 

Please let me know if you would like to give a try again to RepairDesk. I would love to assist you in setting it up again. Thanks.

Regards,
Uzair
Product Manager at RepairDesk
