### ISSUE TITLE
set a customer / customer group to tax exempt?

### ISSUE THREAD

**Issue by Repair-Desk** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#344]
Is there a way to set a customer / customer group to tax exempt?

**Comment by screenfixing** [comment]
Curious if any progress on this roadmap item?

**Comment by Uzair-RepairDesk** [comment]
Hi @screenfixing 
Hope you are doing great
I am glad to inform you that we have added the option to set a specific tax class against a customer and customer group so that you can mark the customer as tax exampt. While adding a new customer from manage customers section or from POS, tax class field can be selected and that will be applied when an invoice is created against that customer. 

Let me know if you have any more concerns to share. 

Thank you
