### ISSUE TITLE
Viewing Item Sold in Transaction Logs

### ISSUE THREAD

**Issue by bharaaus** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#381]
Transaction Log is very helpful throughout the day.
But it will be more convenient if we could see the product name on that section as well.
See attached Pic

![transaction log](https://user-images.githubusercontent.com/34261339/43183169-852524c6-9027-11e8-8733-e91e331c71b5.png)

**Comment by Uzair-RepairDesk** [comment]
Hey @bharaaus 
I believe it is a good idea, however, there are already a lot of relevant fields available in transaction log report. I am afraid if there are multiple payment methods and we display item names as well, it will disturb the UI/UX of the report. 
Thank you for listing it over GIT. I will discuss it with the design team.

**Comment by Uzair-RepairDesk** [comment]
Hey @bharaaus 
As we informed on Facebook user group. We discussed this with Muhammad Fayyaz whose our development lead he has suggested against adding this improvement primarily because in transaction log report we fetch data from different tables and if we add item name information it will increase load time and if an invoice has 50 items it will never open.

**Comment by bharaaus** [comment]
Now i have noticed another bug in this.

It used to be showing the same day log on this page.
Now from last two days, it shows older days details in here too.
It is bit confusing to check what we upto in the middle of the day.

Have a look in picture.
Random old days tranactions are alwasy there.

![transaction logs](https://user-images.githubusercontent.com/34261339/43639303-2166f84e-975f-11e8-8e75-92d3b69f9404.png)
