### ISSUE TITLE
Missing transaction

### ISSUE THREAD

**Issue by JessicaSOS** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#407]
1) Where is the history between the 2 in inventory and the 0?
2) Why it is 1. What was the transaction?
SOS Phone Limoilou item #9557
<img width="949" alt="item 9557" src="https://user-images.githubusercontent.com/40500094/44224901-f63aa580-a159-11e8-9451-39579ff8a250.png">

_--
french:
1)Où est l'historique entre les 2 en inventaire et le 0?
2) Pourquoi il est a 1. Quelle a été la transaction?
SOS Phone Limoilou item #9557_

**Comment by usmanalikhan93** [comment]
Hi @JessicaSOS 

Sorry for the inconvenience. 
We are reviewing this issue internally. Once I get something on this, I will circle back to you. 

Usman Ali.

**Comment by usmanalikhan93** [comment]
Hi @JessicaSOS

I have come up with one use case after testing, this issue comes is case of e.g. when you are logged in on store A and in inventory transfer you select from store B and to store C, it does not log history against that inventory. So for now I recommend you that please select from store in which you are logged in.

Furthermore, I am discussing this with developer for log transfer history in this case. I will update you when I get more info on this.

Usman Ali

**Comment by usmanalikhan93** [comment]
Hi @JessicaSOS 

I hope you are doing well. We have released a fix for this issue as I have mentioned the use case earlier. Now history will be come up in inventory in these cases. I hope in future, you will not face these issues again related to missing transactions. 

For now I am closing all tasks you reported related to missing inventory.

**Comment by JessicaSOS** [comment]
I will wait for your news for the rest. The problem with these tasks may be related: # 407, # 418, # 432 ...
