### ISSUE TITLE
Sorting in Customer Details

### ISSUE THREAD

**Issue by itzcomputers** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#431]
I have brought this up before, but nothing seems to have been done about it.

So you can sort jobs on a customers detail page possibly by date or ticket ID, problem is there is no order to it. So when im trying to find the customers latest job and sort by date or ticket ID there seems to be no rhyme or reason to its results. This can be verified on any of my regular customers. Only one of many issues  but do something about it....

**Comment by Uzair-RepairDesk** [comment]
Hey Michael @itzcomputers 
We already placed your request in our Roadmap earlier when you requested it. 
#349 
Good News is that we have prioritized it to do it in this week. I will update you once its done. Thanks

**Comment by Uzair-RepairDesk** [comment]
Hey Michael @itzcomputers ,
Hope you are well. This is to inform you that we have made improvements based on your request. On customer details page, tickets and invoices listing data will display in order now. You can also sort tickets and invoices listing with respect to "ID" and "Date". 
Note: You need to click on "Date" twice if you want to sort tickets/invoices from "Date" field because system clears the ID sorting first and then sort the listing with dates. 

Please review at your end and I hope that if there’s anything else I can do for you, you won’t hesitate to let me know. Thanks
