### ISSUE TITLE
Need Item Description Printed Out on Receipt

### ISSUE THREAD

**Issue by BharatPRC** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#441]
Currently, Item Description is only get printed out on A4 Invoice, But on Thermal Invoice, its not showing.
Can you plz enable this option. ? ( Staff saying it used to print out before, but i dont remember )

The main reason for this is for SPECIAL TERMS & CONDITION.

When we sell phones, it has special terms, and we mention them in Description.
So when we print out invoice, it shows that to customer.

**Comment by Uzair-RepairDesk** [comment]
Hey @bharaaus 
Thank you for highlighting this. However, we never had this option or "Description" tag under "Thermal Receipt" to display for each line item. The reason is "Thermal Receipt" is short in size. 
I really appreciate that you took the time to share it with us. 

We have a plan to improve "Template Editor" functionality in the next quarter so we can accommodate your above feedback in the improvements to add a "Description" tag under "Thermal Receipt". Thank you for your understanding.

**Comment by rlltd** [comment]
Hi,
I think this is a great idea. We have special terms on things like batteries (how to treat them and what voids the warranty), and as the OP mentioned, a phone with one feature not working, like Touch ID, should be printed on the thermal receipt to avoid any confusion or conflict with a customer. We only use thermal receipts in my shops and I don't care if a thermal receipt is 1 metre long, as long as it has all the relevant details I need on it.

The only problem is that when printing a long thermal receipt for me, is that RepairDesk (or maybe printnode) shrinks the whole contents into one small length making it impossible to read. It should just print as much as it needs.

**Comment by bharaaus** [comment]
Yes rlltd,
I have noticed that as well. 
When we sell 5 items or more in one transaction then we can not read anything because text shrinks too much. 
And I had tried changing the receipt size to longer , then it prints good but for 1 item sale it prints a lot of blank paper which is annoying. 

I hope they will bring auto adjust paper size according to text .
