### ISSUE TITLE
Indication if a field is changable

### ISSUE THREAD

**Issue by Trevorshaw7** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#457]
Can you make some sort of indicator for the fields that are changeable? It is sometimes very difficult to know wether a field can be changed as not all colored fields are always changeable.

**Comment by usmanalikhan93** [comment]
Hi @Trevorshaw7 

Can you please elaborate with relevant screenshots ?

**Comment by Trevorshaw7** [comment]
<img width="1196" alt="screen shot 2018-10-08 at 4 59 39 pm" src="https://user-images.githubusercontent.com/43588617/46637930-a0f89000-cb1b-11e8-9fbf-82731f05a114.png">

**Comment by Trevorshaw7** [comment]
Everything in the white box is editable, as is the pending box and the in progress box, but the partial box is not editable. given the pending and in progress box is editable you would think the partial is too, but because there is nothing that sets it apart other than color (and there are so many colors we can not know which ones are editable and which are not).  There are more examples of this.

**Comment by usmanalikhan93** [comment]
Hi @Trevorshaw7 

In Partial case, you have to select status internally. E.g. 2 issues have different status in a ticket, you have to make it same to change the partial status. I hope it helps.

**Comment by Trevorshaw7** [comment]
The problem isn't that I have to change it internally. The problem is not
knowing what I can change from a particular screen.

**Comment by Trevorshaw7** [comment]
I am not asking to be taught. I am more asking for an indicator. I just
don't think we are on the same page on this request.

**Comment by Uzair-RepairDesk** [comment]
Hi @Trevorshaw7 
I apologize if we are not able to answer your question. There is not a specific indicator, however, please note down the following scenario's that allow you to edit fields from Manage Tickets screen.

1: You can change the employee or assign the ticket to another employee from "Assigned to" filed. It's editable. If there are multiple devices in a single ticket, you can assign it to the different employee as well
2: You can change/update "Due Date" filed from Manage Tickets screen. "Due Date" field is always editable. If there are multiple devices in a single ticket, you can change "Dute Date" for each individual device.
3: If there is a single device record in the ticket, you can change "Status" of the ticket from Manage Tickets screen. "Status" field is editable in case of a single record. However, if there are multiple devices in a single ticket, the system doesn't allow you to change the status because each device may have different repair status. So in case of "Partial" status, you cannot change it from Manage Tickets.

Other than above scenario's, no field is editable. 

Hope I am able to answer your question in detail. Please do let me know if you still have any confusion. Thanks.
