### ISSUE TITLE
Ability to Edit Manual In/Out Transactions from History Window

### ISSUE THREAD

**Issue by ThinkDigitalRepair** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#469]
Right now we just... can't :)
![2018-10-10 20_38_18-window](https://user-images.githubusercontent.com/23037821/46779436-a6490c80-cccc-11e8-9f83-d68eb9071e0a.jpg)

**Comment by Uzair-RepairDesk** [comment]
Hi Jonathan @ThinkDigitalRepair,

Hope you are well. Currently, it's not possible to edit the Manual In/Out transaction. Its associated with "Start/End shift functionality". If we give the option to edit the records, it may create disturbance in transaction log and reconciliation of the shift. The major problems will come up if users do it after ending the specific shift. 
We advise you to use "Expense" rather than "Manual Out" that is more advanced functionality. However, you can use "Manual In" functionality carefully to log the incoming payments to avoid the issues. Thanks

**Comment by ThinkDigitalRepair** [comment]
Hi, the reason I needed to edit it is that I deposit at the bank early at times I manual that out. I forgot to change it from manual in to manual out and so now the drawer shows $400 extra instead of $400 less. So since I can’t edit it, I have to manual out $800. This causes an incorrect report. It seems like making it editable only while the shift is open shouldn’t create an issue, since nearly all of our other records are editable

**Comment by Uzair-RepairDesk** [comment]
Thank you for sharing your idea. We are working on documentation for "Validation on deletion and Void records" option. 
I can pass your feedback to my team so they can incorporate your idea in the same document. 
"During the shift, if you log "Manual In/Out" transaction and there is a mistake, we will give an option to "Void" the record so you can void it and make a correction. Once its voided, the impact will be removed from shift record. It will only be possible during a particular shift. If the user ends the shift, it will not be possible to void the record"

And I hope that if there’s anything else I can do for you, you won’t hesitate to let me know. Thanks

**Comment by ThinkDigitalRepair** [comment]
Great, thank you. That would solve my issue. Thanks for the response!

**Comment by Uzair-RepairDesk** [comment]
Hey Jonathan @ThinkDigitalRepair 

We have enhanced our module according to your requirements. Once you log the record for Manual In/Out, you can "Update" it from the report before ending the shift. 
You can check more details from following knowledgebase article:-

https://repairdesk.uservoice.com/knowledgebase/articles/810864-what-is-cash-in-out

Please review at your end. Thanks
