### ISSUE TITLE
EAN13 barcades add an extra digit

### ISSUE THREAD

**Issue by phonefixdfw** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#508]
![image](https://user-images.githubusercontent.com/37640713/48380449-66938d00-e69d-11e8-80e4-3cf3c3764004.png)

![image](https://user-images.githubusercontent.com/37640713/48380463-714e2200-e69d-11e8-868e-ebcc6a08e7d7.png)

i dont really care that it adds the extra #, but when you scan item in POS you have to delete that last number for it to find it. This has to be a bug?

**Comment by phonefixdfw** [comment]
![image](https://user-images.githubusercontent.com/37640713/48380524-b5d9bd80-e69d-11e8-90c7-f50a8f25fc07.png)


![image](https://user-images.githubusercontent.com/37640713/48380554-d30e8c00-e69d-11e8-9c83-c2a5673f00fc.png)

**Comment by phonefixdfw** [comment]
also, i assume this is case bc ean13 is 13 digits, but repairdesk will not allow more than 12 digit in upc box. I need this style format because my scanners never seem to work scanning the other style
![image](https://user-images.githubusercontent.com/37640713/48380633-254fad00-e69e-11e8-9468-99529365b512.png) like that

**Comment by usmanalikhan93** [comment]
Hey @phonefixdfw ,
I have reviewed and verified it with the development team, this is an expected behavior with the EAN 13. System automatically adds the extra number and you are right it doesn't display the result on entering the complete number. However if you click or tap on enter button, system adds that item and it is working fine with the scanner as well.

For the barcode that you want to use. Please change your settings and select barcode type: Code 39. **Steps :** 
- Visit https://app.repairdesk.co/index.php?r=config/inventory 
- Change store type: Code 39 
- Click save.
![code39](https://user-images.githubusercontent.com/39614480/48396335-deb09000-e73b-11e8-8a33-471629dfac75.png)

Hope, you find its solution better.

For any other Query feel free to contact us.

Thanks,
Usman

**Comment by phonefixdfw** [comment]
I am already set to barcode 39, but I still don't think this is how it should act. If it adds extra # when printing the label, it should add it within RD also so that you can search by that. Can it be altered to search for the added number as well?

I did test hitting enter after which I guess works but adds an extra step for no reason

**Comment by phonefixdfw** [comment]
The 'hit enter after' trick doesn't work on store to store transfers, have to delete last digit. I still say this entire thing is a bug

**Comment by phonefixdfw** [comment]
does not work on purchase orders either.

**Comment by Repair-Desk** [comment]
@phonefixdfw Are you still facing this issue?

**Comment by usmanalikhan93** [comment]
Hi @phonefixdfw 

Sorry for the delay. I have again reviewed this issue. As I have come up with that it is working on POS. We have to make it work on inventory count, Purchase order, Transfer order, and RMA. I am reporting this to our dev team. And we will try to release a fix for this in early next week. Thanks for the patience. I will revert back to you once I get more info on this. 

Thanks 
Usman Ali.

**Comment by usmanalikhan93** [comment]
For internal use
https://repairdesk.atlassian.net/browse/REP-1196

**Comment by usmanalikhan93** [comment]
Hi @phonefixdfw 

I hope you are doing well. Your reported issue has been fixed. Please verify at your end and do let us know if you have question.

Thanks!
