### ISSUE TITLE
appointment confirmation page - hours

### ISSUE THREAD

**Issue by phonefixdfw** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#544]
![image](https://user-images.githubusercontent.com/37640713/49834711-b4fe7f00-fd62-11e8-8d9e-b91e8124d899.png)

where is it getting these hours from? I am not aware of having these hours listed anywhere (as they are not accurate)

**Comment by phonefixdfw** [comment]
nevermind, i see in advanced config template now under "On Site Success Page"

can this not pull from same hours listed on the appointments integration?

**Comment by Uzair-RepairDesk** [comment]
Hi @phonefixdfw 
The above screenshot is a success message/email to the customer when the appointment is confirmed from Appointment Calendar Widget.
It's a template that can be edited under Advanced Configuration of the "Appointment Calendar Widget".
Since its a default template with the editable source file, we cannot place individual working hours automatically based on your appointment hours. 
You can either set hours of your appointments or working hours of your operations from the template window. 
I hope it helps.
