### ISSUE TITLE
Tax Exempt on edit ticket is not working

### ISSUE THREAD

**Issue by Repair-Desk** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#557]
On Edit ticket page when you change a tax class from Sales tax to tax exempt it doesn't reset it to zero.

Bad Apple

**Comment by Repair-Desk** [comment]
We're investigating this and hopefully it will be fixed early next week. In the meantime you can reset it on the invoice

**Comment by usmanalikhan93** [comment]
For internal use:
https://repairdesk.atlassian.net/browse/REP-1024

**Comment by usmanalikhan93** [comment]
Please check developer feedback: 

"Its not the issue of Tax Exempt. Price were not changing due to customer group attached with the customer. and calculations are done according to Customer group. don't know the status of client updated or not? And Tax exempt in reported transaction was used with value greater than 0 .so that calculation saved with that Transaction . we cannot update that record. client will not face that problem again with new transactions"
