### ISSUE TITLE
Option to Separate Setting Access by User Role

### ISSUE THREAD

**Issue by ochoaonline** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#610]
Would like to be able to separate Settings access by role 
**For Example Manager Role:** 

1.  Access To Employee Module
2. Module Configuration for: Invoices, RMA, Purchases, Inventory , etc , etc
3. How Did you hear about us

**For Example Owner Role:** 
1. Access to Integrations 
2. Employee Pay 
3. Cash Register , Email & Notifications 

Basically make it a little more custom since currently i can only give them full access to all settings or no access at all,

**Comment by Uzair-RepairDesk** [comment]
@Repair-Desk  I believe he is asking to add drill-down permissions for settings

**Comment by Uzair-RepairDesk** [comment]
Hey Modesto @ochoaonline

This is to update you that we are working on the documentation to start working on it. 
We are expecting to start development next week. Thanks

**Comment by ali-repairdesk** [comment]
Hello,

As per discussion with @ochoaonline , Wages can only be done by Super Admins , Store Owners who have Access to all settings on back end, he is not able to set Employee Wages.

Please have this catered in the same task.

Regards,

**Comment by ochoaonline** [comment]
Thank you all

**Comment by ochoaonline** [comment]
@Uzair-RepairDesk Hello Uzair, on this settings section i know you guys are working to be able to sectionalize settings to different users, in the meantime if this is easier if there's a way to remove this option from all stores Except Control Center. , some of the main stuff i dont want them having access to is Business Wise settings and this is one of the big ones 

![drphonefix hq retail settings stores](https://user-images.githubusercontent.com/35181467/53120425-d082c480-351f-11e9-86bf-19fe111f691d.png)

**Comment by Uzair-RepairDesk** [comment]
Hey Modesto @ochoaonline
The reason for this specific trigger is because most of the customers request that if they create new inventory/services other than the control center, they still want to create them in other stores. 
If you don't want to make it possible, I will recommend you to keep it "**NO**" for all other stores. 
I also advise you to restrict specific employee roles to access/update setting so only specific admin roles can update the settings. 
You can also add a new security check to restrict employees to enter "Employee Access PIN Before settings" so you can track it the from employee activity log report. 
**Please check the relevant screenshots attached.** 

![uzairshah roles permission1](https://user-images.githubusercontent.com/22955861/53147664-0bd9cd80-35ca-11e9-9da9-91fc1c0300f6.png)

![uzairshah manage security checks](https://user-images.githubusercontent.com/22955861/53147666-0c726400-35ca-11e9-9b84-70710b3eb325.png)

**Comment by ochoaonline** [comment]
@Uzair-RepairDesk a like that security check, question it there a history for settings? so see who made what change on the settings side Thanks

**Comment by Uzair-RepairDesk** [comment]
Modesto @ochoaonline
You can track it from "Employee Activity log" report:-
https://app.repairdesk.co/index.php?r=stats/employeeActivityLog

**Comment by Uzair-RepairDesk** [comment]
**Update:** We have completed the development of this module and under final testing. We are expecting to make it LIVE in next release.

**Comment by Uzair-RepairDesk** [comment]
Hey @ochoaonline 
We have enhanced the "Employee Roles Permissions" module. We have added separate permissions for complete "Settings" of RepairDesk. You can select between the different modules settings to give limited access to any employee as required.
Please review at your end and share your feedback. Thanks
