### ISSUE TITLE
Inventory counts are not posting accurate adjustments

### ISSUE THREAD

**Issue by Trevorshaw7** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#631]
Inventory counts are not posting accurate adjustments
<img width="1430" alt="screen shot 2019-01-28 at 12 57 28 pm" src="https://user-images.githubusercontent.com/43588617/51862685-5d10dd00-22fc-11e9-880b-e555728a3270.png">
<img width="1429" alt="screen shot 2019-01-28 at 12 57 20 pm" src="https://user-images.githubusercontent.com/43588617/51862693-60a46400-22fc-11e9-8f66-c7d050e95b5b.png">
<img width="1388" alt="screen shot 2019-01-28 at 12 56 52 pm" src="https://user-images.githubusercontent.com/43588617/51862696-64d08180-22fc-11e9-960b-1f158c499c49.png">

**Comment by Trevorshaw7** [comment]
The cost variance is so off as well. It is not even close to accurate.
<img width="1425" alt="screen shot 2019-01-28 at 1 00 59 pm" src="https://user-images.githubusercontent.com/43588617/51862896-e0cac980-22fc-11e9-8686-8aeaf3fbde62.png">

**Comment by usmanalikhan93** [comment]
Hi @Trevorshaw7 

Thank you for bringing this to our attention! It looks like there's a bug that just popped up. 
I'm gonna reach out to our Engineers to get this taken care of, I'll get back to you as soon as I have more information!

For internal Use: 
https://repairdesk.atlassian.net/browse/REP-1257

**Comment by Uzair-RepairDesk** [comment]
Hey @Trevorshaw7  
Hope you will be fine, 
1. Your reported issue regarding posting to count entries to adjustment report has been fixed and live. Can you please check and verify?
2. Your reported issue of variance on Inventory count listing page is due to the reason that there are a number of items in the count, few counts have positive value and others have negative count. This is specific reason, it shows a change in variance on count listing page. Perhaps it seems to be annoying and difficult to understand. We will discuss it in-house to improve the view of count on inventory count listing page.
