### ISSUE TITLE
Not all Adjustments are being recorded

### ISSUE THREAD

**Issue by Trevorshaw7** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#636]
Not all Adjustments are being recorded
<img width="1430" alt="screen shot 2019-01-30 at 7 37 48 pm" src="https://user-images.githubusercontent.com/43588617/52026974-fee42580-24c6-11e9-83ce-ec6743c7dff4.png">
<img width="1419" alt="screen shot 2019-01-30 at 7 38 00 pm" src="https://user-images.githubusercontent.com/43588617/52026975-fee42580-24c6-11e9-8e35-a7ccdda5cbf2.png">
<img width="1127" alt="screen shot 2019-01-30 at 7 38 35 pm" src="https://user-images.githubusercontent.com/43588617/52026976-ff7cbc00-24c6-11e9-94f5-031435d41d4e.png">

**Comment by Uzair-RepairDesk** [comment]
Hi @Trevorshaw7 
I have checked the above reported issue. There is only specific adjustment entry in the item admin history and we can certainly track it from "Adjustment report". 
Please check screenshots attached. 
Can you please provide more information on this?

![bad apple edit mobile accessories parts iphone 7](https://user-images.githubusercontent.com/22955861/52033012-34c7ef00-2545-11e9-8a69-e621dff7ff20.png)

![item](https://user-images.githubusercontent.com/22955861/52033013-34c7ef00-2545-11e9-81d5-ef5ce4e3ae8b.png)

**Comment by Trevorshaw7** [comment]
Look between 1-14 and 1-21.  How did those QTY change?

**Comment by Uzair-RepairDesk** [comment]
Thank you for highlighting this. The missing quantity from admin history is actually transferred to Warehouse to Valley Fair that increased the on-hand quantity of the item. Somehow, the log is not coming to the Valley fair store who received the items because of the same transfer order issue for serials we are working on and expected in the coming release.
Please check screenshot from transfer order attached. 
![bad apple transferorderdetail inventorytransfer](https://user-images.githubusercontent.com/22955861/52036413-ec153380-254e-11e9-81d0-8436754fb73e.png)

**Comment by usmanalikhan93** [comment]
For internal use 
https://repairdesk.atlassian.net/browse/REP-1279

**Comment by usmanalikhan93** [comment]
Hi @Trevorshaw7 

Reported issue has been fixed. Please verify at your end and do let us know if you have any question. 

Thanks.
