### ISSUE TITLE
Inventory Transfers are duplicating

### ISSUE THREAD

**Issue by Trevorshaw7** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#647]
<img width="1409" alt="screen shot 2019-02-02 at 12 31 58 pm" src="https://user-images.githubusercontent.com/43588617/52168358-a68b6e80-26e6-11e9-840d-89203fc95546.png">

**Comment by Uzair-RepairDesk** [comment]
@usmanalikhan93 
It should be reproduced as its important. Please discuss it with the development team. Thanks

**Comment by usmanalikhan93** [comment]
Sure @Uzair-RepairDesk I am reviewing this issue and trying to reproduce this issue on my test account.

**Comment by usmanalikhan93** [comment]
For internal use
https://repairdesk.atlassian.net/browse/REP-1305

**Comment by usmanalikhan93** [comment]
Hi @Trevorshaw7 

@Trevorshaw7 there are two solution for this: 

1) We can update your respective inventory with quantity and log will be remain same. Because if we delete any log, it will create problem.
2) Just receive this  transfer in another store and from that store, transfer back your inventory in Warehoue. It will not disturb anything. 

Although developer has put a check on it and hopefully it will not come again. 

Will wait for your response.

**Comment by usmanalikhan93** [comment]
Hi again @Trevorshaw7   - since I haven't heard back from you, I’m assuming you're all set for now, but you can always give me a shout here if anything else comes up!

Thanks
