### ISSUE TITLE
The signatures in widget

### ISSUE THREAD

**Issue by JessicaSOS** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#692]
The signatures do not work this morning in the widget, in all store. Yet nothing was changed and Saturday everything worked well. Can you fix that and stop breaking what works well.

--
french:
Les signatures ne fonctionnent pas ce matin dans le widget, dans toutes les boutiques. Pourtant, rien n'a été changé et samedi tout fonctionnait bien. Pouvez-vous corriger ça et arrêter de briser ce qui fonctionne bien.

**Comment by Uzair-RepairDesk** [comment]
Hey @JessicaSOS 

In order to improve software browsing faster, we've created a custom domain for SOS Phone team which they can use to access RepairDesk below. Please have your team bookmark the URL for easier access:

DOMAIN: https://sosphone.repairdesk.co/ 

**Usman sent you an email on this as well.** 

Please note that you need to update following widget iframe code on your website:
•	Repair Tracker
•	Appointment Calendar
•	Buyback Widget
•	Self Check-In Widget

Moreover, if you're using a customer-facing display you'll need to re-create the URL and open it on your iPAD.

Once you update, it will work fine. Hope it helps.

**Comment by JessicaSOS** [comment]
I understand well thank you very much
fixed

**Comment by JessicaSOS** [comment]
Perfect tnx

 




	Jessica Fugère
Vice-présidente, SOS Phone

 <tel:4189991579> 418 999.1579 |  <tel:4506771579> 450 677.1579 |  <tel:18559991579> 1 855 999.1579 
 <mailto:jessica@sosphone.ca> jessica@sosphone.ca
 <https://sosphone.ca/?utm_source=signature&utm_medium=urlsite&utm_content=sosphone.ca&utm_campaign=outils> sosphone.ca
5375, boul. Guillaume Couture, Lévis, G6V 4Z3
2750, 1re Avenue, Limoilou, G1L 3N8
977, route de l'Église, Ste-Foy, G1V 3V3
835, rue St-Joseph Est, St-Roch, G1K 3C8
926, boul. Sainte-Foy, Longueuil, J4K 1V7

 <https://www.facebook.com/sosphonecanada/> 

 

 

De : Muhammad Uzair Shah <notifications@github.com> 
Envoyé : 26 février 2019 00:06
À : Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS <RepairDesk-BUGS-IMPROVEMENTS@noreply.github.com>
Cc : JessicaSOS <jessica@sosphone.ca>; Mention <mention@noreply.github.com>
Objet : Re: [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS] The signatures in widget (#692)

 

Hey @JessicaSOS <https://github.com/JessicaSOS> 

In order to improve software browsing faster, we've created a custom domain for SOS Phone team which they can use to access RepairDesk below. Please have your team bookmark the URL for easier access:

DOMAIN: https://sosphone.repairdesk.co/

Usman sent you an email on this as well.

Please note that you need to update following widget iframe code on your website:
• Repair Tracker
• Appointment Calendar
• Buyback Widget
• Self Check-In Widget

Moreover, if you're using a customer-facing display you'll need to re-create the URL and open it on your iPAD.

Once you update, it will work fine. Hope it helps.
