### ISSUE TITLE
Statut tradein

### ISSUE THREAD

**Issue by JessicaSOS** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#750]
I do not know if others have been deleted or modified, but I am no longer able to find the status "pending refurb". All the trades I had with this status went into "in stock" for no reason. Status no longer exists Can you help me please.
exemple: SKUxxx9981    SKUxxx2974

--
french:
Je ne sais pas si d'autre ont été effacer ou modifier, mais je ne suis plus capable de trouver le statut "pending refurb". Tous les tradein que j'avais avec ce statut se sont mis en "in stock" sans raison. Le statut n'existe plus. Pouvez-vous m'aider svp.

**Comment by usmanalikhan93** [comment]
Hi @JessicaSOS 

Usman Ali here, Sure thing! Let me take a look to see if I'm getting the same issue as you and I'll circle back to you.

**Comment by usmanalikhan93** [comment]
Hi @JessicaSOS 

It may be because now when you mark your refurb ticket as "repaired and collected" your trade in status will be "in stock". Can you please check this ? 

Or Send me just store name and trade in item id.

**Comment by JessicaSOS** [comment]
SOS Phone limoilou, sample item # 11246 & # 11225

And as you say, it's when the status of the ticket is "completed" or "repaired and collected" that the status disappears.

--
french:
SOS Phone limoilou, exemple item #11246 & #11225

Et comme vous dite, c'est lorsque le statut du billet est "completed" ou "repaired and collected" que le statut disparait.

**Comment by JessicaSOS** [comment]
As the status "scrapped for part" can not be changed. I have 2 phones that share error got into this status. Can not change the status "scrapped for part" ... not very practical!

--
french:
Comme le statut "scrapped for part" ne peut pas être modifié. J'ai 2 téléphones qui part erreur se sont mis dans ce statut. Impossible de changer le statut "scrapped for part"... pas très pratique!

**Comment by JessicaSOS** [comment]
It's really annoying what you did with the statutes. One item was sold and put back in inventory by mistake. Impossible to put it again "sold" even if it is sold. I would like you to return the statutes accessible as before.
Exemple: #11024 Ste-Foy store
--
French:
C'est vraiment agaçant ce que vous avez fait avec les statuts. Un item a été vendu et remis en inventaire par erreur. Impossible de le mettre à nouveau "sold" même s'il est vendu. J'aimerais que vous remettiez les statuts accessible comme avant svp.
Exemple: #11024 Ste-Foy store

**Comment by Uzair-RepairDesk** [comment]
Hey @JessicaSOS 

We have implemented validations on Trade In statuses to avoid problems in Trade in report and analysis. You also reported few issues when you faced few issues with reporting. 
The reasons for all the issues are because of the random behavior of statuses. 

**Please check few scenarios that we updated because of the following reasons:-**

1: If a trade-in device is "**In Stock**" you cannot mark its status "Sold" directly because if it's sold there must be an Invoice reference. With the new update, the status of trade in is "Sold" when you actually sell it with the invoice. 

2: When the status of the device is "**Sold**" it means you have sold the device and you cannot directly mark it "**In Stock** directly. Before the update, if you mark sold device to in stock again, it used to bring out the real problem in reporting. The only way to have it "In Stock" again when you actually make a refund and add device back into inventory. 

3: Pending Refurb status is marked when you create "Reburbishment Ticket" and its back "In Stock" again when you complete the refurbishment ticket. Please let me know if it's working for you?

_**Regarding your "Scrapped for Parts" case, we can look into it to update so you should be able to mark any other status except "Sold". I will discuss it with the team to update it.**_

I apologize for the instant changes however all the updates are to make specific standards that will help to avoid the problems in reporting and sales insights. 

If you have any further questions, please feel free to ask.

**Comment by JessicaSOS** [comment]
I have to send phones for repair and it is impossible to put them in pending refurb. Can you quickly correct please, all status starts to be mixed and they do not represent anything anymore.

**Comment by usmanalikhan93** [comment]
Hi @JessicaSOS 

For this flow you can add a new custom status as "Pending Refurb". So when you want to manually add this status you can change it when you want. I hope this will works for you. 

Thanks 
Usman Ali.

**Comment by JessicaSOS** [comment]
I understand what you said, but if I use a status "pending refurb custom" the true "pending refurb" will no longer serve any purpose. In addition, the automatic status that goes into "pending refurb" when creating a ticket will no longer work.

Also, what comes into conflict are devices that I have repaired before selling them. As soon as the status of the repair ticket is set to "repaired", the status of the tradein puts it in "in stock". Yet, just because the phone is repaired does not mean that it is necessarily ready to sell. We must first receive it (when it has been repaired in another branch), test it, unlock it, label it, etc ... It should not be put in "in stock" as soon as the technician has finished the repair.

--
french:
Je comprends ce que vous dite, mais si j'utilise un statut "pending refurb custom" le vrai "pending refurb" ne servira plus à rien. De plus, l'automatisme du statut qui se met en "pending refurb" lorsque l'on crée un billet ne fonctionnera plus. 

Aussi, ce qui entre en conflit sont des appareils que je fait réparer avant de les vendre. Aussitôt que le statut du billet de réparation est mis en "repaired", le statut du tradein ce met en "in stock". Pourtant, ce n'est pas parce que le téléphone est réparé qui est necessairement prêt à vendre. Nous devons premièrement le receptionner (lorsqu'il a été réparé dans une autre succursale), le tester, le deverouiller, l'étiquetter, etc... Il ne devrait donc pas se mettre en "in stock" dès que le technicien à terminé la réparation.

**Comment by usmanalikhan93** [comment]
Hi @JessicaSOS 

I understand but we have also maintain a standard so only I can say you is that you can use another workaround by creating custom status for that. Those phones which were repaired but not ready for sale, you can change there status by any custom status. And when they are good to sale, you can change back it as "in stock". I hope it will help. 

Thanks 
Usman Ali
