### ISSUE TITLE
Request - Add images to manufacture and devices

### ISSUE THREAD

**Issue by phonefixdfw** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#770]
On POS, there is option to add image on category and part, but not manufacture, device, and problem. Would be nice if all 5 steps had images for fast selection

![image](https://user-images.githubusercontent.com/37640713/55984583-6bb43280-5c63-11e9-8dad-2de36db3145f.png)
![image](https://user-images.githubusercontent.com/37640713/55984606-740c6d80-5c63-11e9-8278-58449641cb42.png)
![image](https://user-images.githubusercontent.com/37640713/55984638-7c64a880-5c63-11e9-9134-58707ac1cbe7.png)
![image](https://user-images.githubusercontent.com/37640713/55984664-8d151e80-5c63-11e9-85bf-e7821e15b5fe.png)
![image](https://user-images.githubusercontent.com/37640713/55984692-99997700-5c63-11e9-866a-aabeb50c242e.png)

**Comment by Uzair-RepairDesk** [comment]
Hi @phonefixdfw 
Thank you for sharing your idea. There is no problem to display "Manufactures" or "Devices" images on POS but we have to keep POS super fast so you can quickly check-in. Images always take time to load that impacts the loading speed. 
I will still discuss it in-house to check the possibility to enable images on POS. Thanks

**Comment by Uzair-RepairDesk** [comment]
Hello @phonefixdfw 
You can now enable "Manufacturer" images to show on POS. You can go to Store Setting > Module Configurations > POS and enable the trigger "Show Images of Manufacturers". 
Please make sure that you upload images of each manufacturer under the "Manage Manufacturer" section. 
Currently, it's not possible to show "Devices" images because of the loading speed. 

Hope it helps. Thanks.
