### ISSUE TITLE
Error in status ticket

### ISSUE THREAD

**Issue by hitman1986** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#810]
When I add any payment for any ticket that has not yet expired, it has been repaired and completed, but I do not activate the option to end the repairs.why?
(Just on ipad app)

**Comment by usmanalikhan93** [comment]
Hey @hitman1986 
 
Usman Ali here 👋 Sure thing! Let me take a look to see if I'm getting the same issue as you and I'll circle back to you.

**Comment by usmanalikhan93** [comment]
Hi @hitman1986 

We have reviewed your concern and fond that may be you have enabled this trigger "Close Ticket once invoice is created" which is in Settings > Module Configuration > Tickets. That's why your ticket status gets completed when add payment of it. Please unchecked it and then try again. If you find any confusion do ask me. 

Thanks
Usman Ali

**Comment by hitman1986** [comment]
Thank you
