### ISSUE TITLE
Life Time Warranty

### ISSUE THREAD

**Issue by Omar1892** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#812]
Hello, 

In the life time warranty their should be an option in witch we can set a limit of how many times the warranty can be claimed. This could be applied to all types of warranties. Because so far the costumer can come in for a warranty replacement but theirs no record that pops up when a costumer has come in once or twice for a warranty replacement.

**Comment by Uzair-RepairDesk** [comment]
Hi @Omar1892 

Hope you are well. Currently, if you set "Lifetime warranty" you can claim warranty multiple times. If you are claiming it for "Repair parts" from the ticket section, you can track it from "Admin History" of a specific ticket where it shows that part is marked "Faulty/Broken".
Moreover, if you are doing for a repair service, you can search for tickets for a specific customer to see the tickets created in warranty claim against a repair service.

If you want to do it for a specific limit of time, you can either set a specific duration of warranty rather than to set it "lifetime".

Hope it helps.

**Comment by Omar1892** [comment]
It makes since what you saying. But even if we set the warranty for 90-Days for example and our store terms and condition are that a costumer can only come in for 3 warranty claims during the 90-Days warranty. And they come in a 4th time during the 90-Days their should be a limit of how many times they can claim the warranty. The limit should be marked as "limit has been reached" or a pop up screen of some sort. I do understand that we can see the costumer history, but in most cases shop are really busy with other repairs that by just simply trying to figure out how many warranty repair this costumer has come in during the 90-Days will be hard since we have to open the ticket and find out if the device they are bring in is the device that they didn't bring in last time. By applying a limit, this limit can be applied to a "limited life time warranty".
