### ISSUE TITLE
Allow for multiple 'Manufacturer' and 'Devices' to be selected

### ISSUE THREAD

**Issue by benjamingartner** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#837]
Currently if i was to create a new product like a Wireless Charger for mobile phones which works for both Samsung and Apple devices (etc) it only allows for one to be selected. 

It would be better if the options were box selections to allow for multiple selections.

![image](https://user-images.githubusercontent.com/39751801/60963668-faf4e300-a343-11e9-9801-4ee72661b821.png)

**Comment by Uzair-RepairDesk** [comment]
Hey Benjamin @benjamingartner 

Thank you for sharing your idea. Currently, you can associate a single item with multiple devices. If you want to add it with a different manufacturer we advise to add a new product with a different manufacturer and its supported devices.

We are not able to allow selection of multiple manufacturers because of cross impacts while a selection of Manufacturer and its associated device when you sell or associated item with tickets (in case of part items). 

We also need to differentiate items in reports like "Sales by Item type" report where there should be a single manufacturer associated with an item. 

Hope you can understand the above constraints to keep it in this way. Thanks
