### ISSUE TITLE
SMS Broadcast Two Way SMS Integration

### ISSUE THREAD

**Issue by BG-RLTech** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#843]
Looking to enable the SMS Broadcast 2 Way Message integration a few questions before we pay out. 

Scenario 1: We advertise the mobile number and a customer initiates a sms (not rply message) what happens to that message? Does it go to RepairDesk? If so how does it display/be received.

Scenario 2: We send the customer a message and the customer reply's. Is it the case of:
- If the message is sent from customer profile the reply goes to the customers profile
- If the message is sent on a ticket the reply goes to the ticket

If this is the case how are you notified that there is a new reply message from the customer or do you have to review the tickets/profiles all the time to see the replies?

![image](https://user-images.githubusercontent.com/39751801/61094770-26321c00-a483-11e9-9fff-b603da7ada94.png)

**Comment by Uzair-RepairDesk** [comment]
Hi Benjamin, @benjamingartner 

Please find answers to your each question below:-

Scenario 1: We advertise the mobile number and a customer initiates a sms (not rply message) what happens to that message? Does it go to RepairDesk? If so how does it display/be received.
**It's not possible to directly receive SMS. Since SMS Broadcast is 3rd party integration for 2-way SMS so you need to send a request from RepairDesk to receive a response back.** 

Scenario 2: We send the customer a message and the customer reply's. Is it the case of:

If the message is sent from customer profile the reply goes to the customers profile
**Yes, if you send it from customer profile you can receive a response back under customer profile**

If the message is sent on a ticket the reply goes to the ticket
**Yes, if you send it from a specific ticket you can receive a response back under same ticket**

If this is the case how are you notified that there is a new reply message from the customer or do you have to review the tickets/profiles all the time to see the replies?
**We have a feature available under "Alert Settings" of SMS Broadcast where you can select employees to whom you want to notify. Once you set alert for an employee, he/she can get an alert in RepairDesk once you receive SMS back from a customer**

You can review complete details of integration from the following knowledgebase article:-
https://repairdesk.uservoice.com/knowledgebase/articles/784326-how-can-i-setup-sms-broadcast-api

Hope it helps
