### ISSUE TITLE
Modify Inventory Adjustment Report

### ISSUE THREAD

**Issue by rajeshdungrani** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#862]
I would like you to add Item Name and Cost in Inventory adjustment report.
![image](https://user-images.githubusercontent.com/12892217/61705210-fcba9f80-ad62-11e9-82db-56d931edf6c9.png)

**Comment by rajeshdungrani** [comment]
Waiting for an update

**Comment by Repair-Desk** [comment]
**Hello @rajeshdungrani 👋** 

Happy to help with this. At present, if you click on inventory adjustment ID e.g. Adj-005 which is in blue color in your shared screenshot it opens a detailed report that displays item name, unit cost and other details. 

Since each inventory adjustment report can have multiple items it will create confusion for other merchants when they're looking at this report.

With a small team and a big roadmap, we have to pick new features based on the value they’ll add to the most merchants possible. At the moment, we won’t be able to make this one work during 3rd Quarter. 

And I hope that if there’s anything else I can do for you, you won’t hesitate to let me know.

Regards,
**Usman Butt
Founder | RepairDesk**

**Comment by rajeshdungrani** [comment]
Currently you have provide 2 ways for inventory adjustment.
Method 1 : From Inventory Management 
http://postimg.cc/YhNqR7bC
Method 2 : From Inventory Count
http://postimg.cc/4n6gk5t8
Now you have merged both adjustment in your "Inventory Adjustment"
Now if you consider Method 1 only, then you can get the report I am looking for. Actually, I would like to use this feature as "Purchase of Spares" on the fly without making purchase order.
