### ISSUE TITLE
Tickets panel is always hiding closed tickets

### ISSUE THREAD

**Issue by ben-ihelputech** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#878]
When I search for a customer who's ticket has closed out, it will always hide the ticket regardless of whether or not the "Hide Tickets" button is checked. This is frustrating as it makes it difficult to search for a customer's ticket when you need to reference something.

**Comment by Repair-Desk** [comment]
Hello @ben-ihelputech,

Happy to help with this. Can you please check if you've following trigger switched on "Hide Closed &: Cancelled Ticket on Listing page" 

In the meantime I'll work with the development team so that even if a trigger is switched on and you search for a closed ticket it should display in search results.

**Comment by usmanalikhan93** [comment]
Hi again @ben-ihelputech  - since I haven't heard back from you, I’m assuming you're all set for now, but you can always give me a shout here if anything else comes up!
