### ISSUE TITLE
Error in search invoice

### ISSUE THREAD

**Issue by hitman1986** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#890]
When search any invoice in invoice manage by customer name in arabic language not showing any result,
And new issue :
When press export excel in search invoice after showing result not export any file why?!

**Comment by usmanalikhan93** [comment]
Hello @hitman1986 ,
Sorry for the trouble. We have created a ticket for the development https://repairdesk.atlassian.net/browse/RB-355.

Issue 2:
We have verified this scenario it is working fine at our end. Can you please share the video so we can drill down the root cause of the issue. I hope it will work better for us.

Thank you for your patience and time.

**Comment by hitman1986** [comment]
Im sended video to mr danish
When search invoice by customer group or customer name and export result to excel not export it.

**Comment by usmanalikhan93** [comment]
Hi @hitman1986 

Your issue no. 1 is fixed. Please check this at your end.

**Comment by hitman1986** [comment]
Thank yo issue no. 1 it fixed and no. 2 is fixed thank you
