### ISSUE TITLE
Easy to use po

### ISSUE THREAD

**Issue by hitman1986** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#900]
When you make purchase order first select supplier and then select item by search name,
Can you when tybing the name of item just show item from this supplier and skiping other item ?

**Comment by Uzair-RepairDesk** [comment]
Hey @hitman1986 

Thank you for your suggestion. Currently, we allow users to select a specific supplier but we give an option to select any specific item for a purchase order. The reason is that you might purchase an item from different suppliers. We have "Multiple Supplier SKU" and "Serialized Inventory" feature available for the same reason. 

https://repairdesk.uservoice.com/knowledgebase/articles/1190947-how-to-add-multiple-sku-s

https://repairdesk.uservoice.com/knowledgebase/articles/930741-serialized-inventory

Currently, we cannot restrict to bring items in search relevant to a supplier only. 

Thank you for your understanding.
