### ISSUE TITLE
Ticket search

### ISSUE THREAD

**Issue by JessicaSOS** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#908]
Can not search for a ticket by entering a date or status. No results are displayed.
<img width="938" alt="ticket search" src="https://user-images.githubusercontent.com/40500094/63283754-0d860480-c280-11e9-8d11-6c48e0d1b482.png">

--
french:
Impossible de rechercher un ticket en entant une date ou un statut. Aucun résultat ne s'affiche.

**Comment by usmanalikhan93** [comment]
Hi @JessicaSOS 

I have checked this on your account and it looks like it is working fine. You have to apply created date filter for 5th May 2019 to 29th Jun 2019 and you will see the tickets but there is no repaired tickets in that. You are not fetching data because you are also applying due filter 5th May 2019 to 29th Jun 2019 and none of the ticket has this date. Please check again and do let me know if you have any question. 

Thanks 
Usman Ali

**Comment by JessicaSOS** [comment]
If I use Search Filter and select "creation date" from May to July 2019 and click on search (without any other filters), I only have 4 results. As if in 3 months I would have created 4 results only.
<img width="944" alt="4 result" src="https://user-images.githubusercontent.com/40500094/63354429-69a96100-c332-11e9-8cb3-5ae66b4f7cf1.png">

**Comment by usmanalikhan93** [comment]
Hi @JessicaSOS 

I have checked in you account and found that you have enabled these triggers that's why it is showing you less results while search. 
![Jessica_902](https://user-images.githubusercontent.com/39614480/63409868-72219a80-c40b-11e9-8929-53eeeea7e481.png)

**Comment by JessicaSOS** [comment]
These triggers were not changed and it worked well before. Closed notes never appeared. The problem is open tickets; "waiting for part", "waiting on customer", "waiting for received", "in progress" and others ...
