### ISSUE TITLE
Quick Improvement - Default Repair Time Due Adjustable 

### ISSUE THREAD

**Issue by jpcodev** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#916]
Hey Team, 

When we are checking customers in for repairs through our point of sale system the time due is set by default to 1 hour. 

<img width="280" alt="Screen Shot 2019-08-27 at 10 04 54 am" src="https://user-images.githubusercontent.com/36390402/63731402-b224c980-c8b2-11e9-8d77-93f3f8372cec.png">

Our mobile repair division has a default of 2 1/2 hours for repair time due. In your back end module configuration can you please add an option to select the default amount of time for our tickets.

This process of changing the default time for every customer check in is time consuming and when our shop is very busy it often gets overlooked by the front of house.

Thanks,
John @ iRepairs

**Comment by Uzair-RepairDesk** [comment]
Hi John, @jpcodev 

Thank you for sharing your idea. Currently, the idea is to keep the default 1 hour (60min) time because generally there are 60min repair job services that most of the businesses offer. 
You can also quickly change it according to your schedule while booking a repair job. 

I can certainly see how suggested improvements would be useful if you offer it in 2 and 1/2 hours (150min) and want to make it a default option. Perhaps we can add a configuration to set a default time so "Due Date" should be populated accordingly.  

I am marking it under enhancements to consider it in improvements. I will update the post once it's scheduled and proceed to the development. Thanks

Regards,
Uzair
Product Manager at RepairDesk

**Comment by hjtse** [comment]
BUMP

**Comment by Uzair-RepairDesk** [comment]
Hi @jpcodev @hjtse 

We have made this improvement LIVE. You can now set the default due date & time for repair tickets. 
You can go to Store Settings > Module Configurations > Repairs > Update 'Default due date & time for repairs' > Save

Please have a look at the screenshot attached. 

![Repairs Config](https://user-images.githubusercontent.com/22955861/70715818-e65eb180-1d0c-11ea-9be4-69550edffede.png)
