### ISSUE TITLE
Making customer signature mandatory before creating a ticket or checkout on ipad?

### ISSUE THREAD

**Issue by gijoe911** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#939]
is it possible to make customer signature mandatory before creating a ticket or checkout on the ipad? similar to making referral source a mandatory field when adding new customers. reason being is a lot of staff will miss the signature unintentionally if it's not bounded by the system. thanks

**Comment by gijoe911** [comment]
or make it at least a pop-up question since staff often forgets to ask customers for passcode when dropping off their devices for diagnosis. this would be very helpful and saves lots of time calling back and forth with customers. cheers

**Comment by Uzair-RepairDesk** [comment]
Hi @gijoe911 
Hope you are doing well. 

First of all thank you for making this useful suggestion. I have noted it down and we will surely take this up for you once we are done with the launch of iPad Offline Version. Meanwhile let me assist you with the available work around to cater this problem that you are facing.

 If you want to make passcode as manadatory field, you can easily do that using our **manage custom fields functionality.** From web, you can **set passcode as manadatory field** across all categories and sync it with iPad so that whenever your staff will proceed without entering passcode, it will give an alert message asking your employees to enter passcode while creating ticket. 

This [article ](https://help.repairdesk.co/knowledgebase/articles/1923739-how-custom-fields-work-on-ipad-pos-register-app) can guide you on how to set manadatory fields from web and use them on iPad.

Please let me know if you have further questions and I will be happy to assist. 

Regards,

**Comment by gijoe911** [comment]
thanks usman, while this is not the perfect solution, it's a pretty good workaround.  appreciate your help!
