### ISSUE TITLE
Not able to input alphabetical password on ipad

### ISSUE THREAD

**Issue by gijoe911** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#940]
As titled, this becomes trouble especially when we get computer repairs. Can we solve this?

**Comment by Uzair-RepairDesk** [comment]
Hello **@gijoe911**
Hope you are doing great. 
I am delighted to inform you that we have made this improvement for you and sent a release last week which is expected to get LIVE in a day or two. I will keep you updated on it so that you can check it at your end once the iPad Release 4.4 is LIVE. 

Please let us know if there is something else I can assist you with. 

Kind Regards,

**Comment by Uzair-RepairDesk** [comment]
**Hi @gijoe911** 
Hope you are doing great!

I am delighted to inform you that the above mentioned improvement regarding alphanumeric keyboard for entering pass code has been Live. Please download our latest iPad Release from App Store and verify it at your end. 

If there is anything else we can assist you with, please don't hesitate to reach out to us. 

**Best of Luck,**
