### ISSUE TITLE
Refund payment method 

### ISSUE THREAD

**Issue by Omar1892** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#955]
The way payment methods are done when refunds are issued is confusing. The reason is because we have to refund the costumer on the payment method they choose when they first paid the invoice. For example costumer pays with Debit/Credit card, comes back and wants a refund. The system doesn't block the option to refund the costumer in cash instead it allows us to give them a refund in cash when the payment method was done in credit/debit. All stores in the US have this trigger set up that the store will only refund you on the payment method you choose at check out and the reason is to prevent fraud. Can you guys make it mandatory to refund the costumer depending on the type of method they choose or a trigger to turn it on and off. For those costumer that want it on we can leave it on and those want want it off can leave off. 

![Screen Shot 2019-11-13 at 1 30 14 PM](https://user-images.githubusercontent.com/47898011/68806338-8647f300-061a-11ea-8042-b89ba075fbd3.png)

**Comment by usmanalikhan93** [comment]
Hi @Omar1892 

Thanks for highlighting this. In case of refund, you can select other payment from which it was paid. So it will mark in it.
What you are referring is to we have to mark it as mandatory from where payment has been given, it should comes on refund too ? 

Regards
Usman Ali

**Comment by Omar1892** [comment]
Yeah so the refund should only be given from the payment method they used to make the purchase.

**Comment by usmanalikhan93** [comment]
Hi @Omar1892 

Let me forward this to Product Manager so he can check. 
@Uzair-RepairDesk can you check this ?

**Comment by Uzair-RepairDesk** [comment]
Hi @Omar1892 
Currently, it's not possible to restrict the system to only mark a refund with the same payment method that you take on purchase. 
The reason is that payment can be logged with different payment methods (split payment) on the invoice and also you can make refunds on a specific quantity or amount. 
It will not be possible to recognize the exact payment method in this case. 

However, you can check the payment methods from the invoice and make sure that you log the refund amount with the same payment methods on the checkout screen. 

I hope that if there’s anything else I can do for you, you won’t hesitate to let me know

**Comment by Omar1892** [comment]
Ok, sounds good. Hope fully you guys can do something about it in the future.
