### ISSUE TITLE
When ticket status change to complete, automatically create an invoice and email invoice with link to pay via PayPal.

### ISSUE THREAD

**Issue by hjtse** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#966]
Currently this is done manually, but I want to automate. 

This is especially important since the iPAD POS does not have an option to convert ticket to invoice (See issue https://github.com/Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS/issues/965)

**Comment by Uzair-RepairDesk** [comment]
Hi @hjtse 
I will be happy to assist you with it. 

Currently its not possible to convert a ticket directly to an invoice from iPad app. However you can create an invoice from ticket by re-opening the ticket on POS and checking it out as discussed in the [article. ](http://help.repairdesk.co/knowledgebase/articles/1810417-how-to-convert-a-ticket-into-an-invoice-via-ipad-a)

I have tested your concern regarding the PayPal Payment link but its working fine for me. Can you please make sure that following settings are done properly. 
"The PayPal payment link is sent in email for unpaid invoice from both iPad & web. The Payment link is not sent in case of tickets. Plus there is also a condition i.e. Manage Email/SMS Notifications Settings,    the Payment_link macro should be added in the email else the link won't be sent in the email. You can try it with this macro if it works for you. {payment_button}

Otherwise please share your credentials at **uzair@repairdesk.co** and I will surely look into it for you. 

Kind regards
