### ISSUE TITLE
sms notification problem

### ISSUE THREAD

**Issue by gsmgps-star** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#969]
hi.
we have more than one mobile carrier: 041, 051, 068, 070.
all clients except 070 receive SMS notification.
i bought test 070 number and tested it myself more than 6 times and I haven't received sms even 1 time.

i have number 051 myself and i always get sms.

what is wrong?
Any help please?

**Comment by Afnan-Mahmood** [comment]
Hello @gsmgps-star 

Sorry for the trouble.

I discuss this issue with our development team. This issue is not from our side as from repairdesk provided number forwarded to clickatell than remaining things depends on clickatell. We are really sorry as we can't solve this bug because this is not related to repairdesk.

Can you please contact with clickatell support so they can add 070 to their library. 

Kindly update us as well regarding the clickatell support response that work for you or not.

Hope this helps.

Best,
Afnan Mahmood

**Comment by gsmgps-star** [comment]
ok tnx
