### ISSUE TITLE
Register Sales Report

### ISSUE THREAD

**Issue by rajeshdungrani** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#971]
Can we have an additional column of COGS in Register Sales report. So that we can have a complete view of profitability Invoice wise

**Comment by Uzair-RepairDesk** [comment]
Hi @rajeshdungrani 

Thank you for sharing your idea. I appreciate it. However, it's not possible to show COGS and Profit in the register sales report because of the following reasons:-

1: Register Sales report is on the basis of cash basis accounting. The cash basis is a method of recording accounting transactions for revenue when the corresponding cash is received or payments are made. 
2: If an invoice is partially received, it still logs the transaction in the register sales report where the system cannot determine the associated "COGS and Profit" in any case. 

**If you want to track down the COGS and Profit of one specific invoice, I refer you to review the "Item-wise Sales Report" by applying the criteria from a specific invoice. It will calculate the COGS and associated profit of each item in a specific invoice once invoice is fully paid.**

Please check the screenshot attached.

![uzairshah- Item-wise Sales Report](https://user-images.githubusercontent.com/22955861/69784099-cab8be80-11d6-11ea-85f6-be14e2dfb94b.png)


I hope it helps. Thanks for helping us make this a platform you'll depend on and we hope to support your business for many years to come.
